#!/bin/sh
#
# Command functionality
#
# include a command source
#
# $1 : command name (without full path, but can be a subpath)
#
# @NOTE commands are essentially libraries, but we load them differently
#   as we have multiple locations where they can be


commands_addpath()
{
  list_add "path_commands" "${1}"
}
commands_getpath()
{
  list_get "path_commands"
}

# path to the command shell scripts
commands_addpath "${path_manage}/libraries/command/commands"

# Include a command
command_include()
{

  # Get the command as the first parameter
  local command=$1
  shift

  # define some local vars
  local path=""
  local path_command=""
  local success=-1

  debug --level 8 --topic "COMMAND->INCLUDE->CALL->${command}" "called with \"command_include $@\" [paths:`commands_getpath`"

  # LIBRARY
  case " $included_commands " in
    *" ${command} "*)
      debug --level 7 --topic "COMMAND->INCLUDE" "command already included! [command:${command}][included_commands:${included_commands}]"
      success=0
    ;;

    *)

      # mark success to show that we didn't find the library
      success=-1
      for path_command in `commands_getpath`; do
	path="${path_command}/${command}"

	debug --level 9 --topic "COMMAND->INCLUDE" "checking command path [command:${command}][path:${path}]"
	# do a quick check on if the path exists
	# @NOTE technically we don't need to use this, as load_library does it as well, but we do it just to save effort
	if [ -e "${path}" ]; then

	  debug --level 8 --topic "COMMAND->INCLUDE" "Including command.  Handing off to library_load ==> library_load --library \"command:${command}\" --path \"${path}\" $@"
	  library_load --library "command:${command}" --path "${path}" $@
	  success=$?

	  if [ $success -gt -1 ]; then
	    debug --level 7 --topic "COMMAND->INCLUDE" "Command included [command:${command}]"
	    break;
	  fi

	fi

      done

      if [ $success -eq -1 ]; then
	debug --level 6 --topic "COMMAND:INCLUDE" "Command include failed [command:${command}]"
      fi
    ;;
  esac

  return $success
}

# Execute a command
#
# -a|--action {action} : specify a method to run other than 'execute'
#
# @NOTE the library handler runs a fail if the action fails
command_execute()
{
  local command=$1
  shift

  # include the command source file
  command_include ${command} $@
  if [ $? -eq 0 ]; then

    # default action
    local action="execute"

    while [ $# -gt 0 ]
    do
      case "$1" in
	-a|--action)
	  action=$2
	  shift
	  ;;
	*)
	    break;; # terminate while loop
      esac
      shift
    done

    debug --level 7 --topic "COMMAND:EXECUTE" "command [ ${command} ] handing off to command_execute script: library_execute --action \"${action}\" \"command:${command}\" $@"
    library_execute --action "${action}" "command:${command}" $@
    local success=$?

    if [ $success -eq 0 ]; then
      debug --level 8 --topic "COMMAND:EXECUTE" "${command} succeeded."
    else
      debug --level 6 --topic "COMMAND:EXECUTE" "Command execution failed for command.  Command method returned an error [command:${command}]"
    fi
    return $success

  else
    debug --level 6 --topic "COMMAND:EXECUTE" "Command execution failed.  Could not find command [command:${command}]"
    return 1
  fi
}
