#!/bin/sh
#
# hook:help Main help handler for hook help
#

hook_version="2"
hook_root="hook_help_hook_050"

show_global_hooks="no"

# description method
hook_help_hook_050_description()
{
  echo "Main help handler for hooks"
}

# help method
hook_help_hook_050_help()
{
  echo "
hook->help: Main help handler

This hook is the primary hook help executor for any hook
The hook will search out a hook and provide either a list entry
or a full help description for a hook.
"
}
# description method
hook_help_hook_050_execute()
{
  # hook is the first argument
  local hook="$1"
  shift

  if [ -z "${hook}" ]; then

    hook_help_hook_050_help_generalhelp $@

  else

    debug --level 6 --topic "HOOK->HOOK->HELP-050" "Running help for hook [hook:`hook_label \"${hook}\"`][path:${hook}]"
    if [ -f "`path_expand \"${hook}\"`" ]; then
      echo "
HELP FOR HOOK : ${hook}"
      hook_execute "${hook}" --action "help" $@
    else
      hook_help_hook_050_help_unknownhook "${hook}"
    fi
  fi
}

# method to list all topics in scope
hook_help_hook_050_list()
{
  local scope="$1"
  local states="pre execute post"

  # hook flags
  local flags=""
  while [ $# -gt 0 ]
  do
    case "$1" in
      -s|--state)
        states="$2"
        shift
      ;;

      *)
        break;; # terminate while loop
    esac
    shift
  done

  local hook=""
  local hooks=""
  local state=""
  for state in ${states}; do

    hooks="`hooks_list \"${scope}\" --state \"${state}\"`"

    if [ -n "${hooks}" ]; then
      if [ "${state}" == "execute" ]; then
        echo "HOOKS FOR ${scope}"
      else
        echo "HOOKS FOR ${scope} THAT ACTIVATE IN STATE ${state}"
      fi

      for hook in ${hooks}; do
        echo "--> `hook_label \"${hook}\"` : `hook_description \"${hook}\"` (`hook_helppath \"${hook}\"`)"
      done
    fi
  done
}

# generic help message for the command help system
# @TODO put some usefull material here
hook_help_hook_050_help_generalhelp()
{
  echo "
hook->help->hook->050 : GENERIC HELP MESSAGE GOES HERE

- explain the help system
- explain the hook system

- give examples for showing help for a hook      -> ./command|flow --help {hook:/hook}
"
}
# output message if help is requested for an unknow command
hook_help_hook_050_help_unknownhook()
{
  echo "
hook->help->hook->050 : UNKNOWN hook HELP MESSAGE GOES HERE [hook:$1]

you asked for help information about a hook in the system that cannot be found."
  # Include general help
  hook_help_hook_050_help_generalhelp
}

