#!/bin/sh
#
# library: www-cnpm-jn
#
# A library which includes some useful www server builds, and
# some related settings
#

# The build code should automatically recognize our library
# and our settings are kept in the settings file so we don't
# really need to have anything here yet.
