#!/bin/sh
#
# Feature alias, to load aliased feature components
#"

debug --level 8 --topic "FEATURE->ALIAS" "Feature alias included : $@"

# alias feature target
feature_alias_target=""

while [ $# -gt 0 ]
do
  case "$1" in
    --source-include-path)
      shift
      ;;
    --target)
      feature_alias_target="${2}"
      shift
      ;;
    *)
      break;
  esac
  shift
done

if [ -n "${feature_alias_target}" ]; then
  debug --level 5 --topic "FEATURE->ALIAS" "Feature has been instructed to load a feature [feature:${feature_alias_target}]"
  feature_load "${feature_alias_target}"
fi
