#!/bin/sh
#
# HOOK: INIT:help : describe the flow command
#

hook_root="init_help_010"
hook_version="2"

# description hook method
init_help_010_description()
{
  echo "Init: definition for help"
}

init_help_010_help()
{
  echo "
FLOW: Init

Initialize the current project

"
}

# Execute method - as this is a help hook, it just outputs the help
init_help_010_execute()
{
  init_help_010_help
}