#!/bin/sh
#
# INIT:HOOK: Create the custom project folder
#

hook_version=2
hook_root="hook_init_005"

# descriptoin method
hook_init_005_description()
{
  echo "Create the custom project folder, if missing."
}

# help method
hook_init_005_help()
{
  echo "
hook->init->005 : Create the custom folder for the project

This hook will create a new root level folder for your project
in which all of your settings, and custom project code can go.

The folder will always be /folder

"

}

# execute method
hook_init_005_execute()
{
  # what is the root path to the project folder
  path_data="${path_data:-${path_project}/project}"
  path_data_executable="${path_data}/${path_data##*/}"

  if ! path_is --dir "${path_data}"; then
    debug --level 5 --topic "HOOK->COMMAND->INIT->005" "Making sure that we have a project folder [path:${path_data}]"
    # make sure that we have a custom library in the data path
    path_ensure --dir "${path_data}"
  fi
  if ! path_is --exec "${path_data_executable}"; then
    debug --level 5 --topic "HOOK->COMMAND->INIT->005" "Making sure that we have a project library executable [path:${path_data}]"
    path_ensure --exec "${path_data_executable}"

    echo "#!/bin/sh
#
# Project library handler
#

###
# What to put here
#
# - custom functions for your project
# - a help / helplist handler
#


" > "${path_data_executable}"

  fi
}
