#!/bin/sh
#
# Create the project image build
#

hook_version=2
hook_root="hook_command_init_030"


# description method
hook_command_init_030_description()
{
  echo "Create default project image build"
}

# help method
hook_command_init_030_help()
{
  echo "
HOOK->FLOW->INIT->030: Build the default project image

This hook will run a docker build, createing a new system
image for you to use for your project.

[-t|--template {template}] : specify an specific build that should be used as the new custom build
[-b|--build {build}] : specify an specific build that should be copied as the new custom build
[-i|--image {image}] : specify an image name for the new custom build
[-v|--version {version}] : specify an specific version/tag for the new custom build

"
}

# execute method
hook_command_init_030_execute()
{

  if [ -z "${project_buildtemplate}" ]; then
    debug --level 5 --topic "HOOK->COMMAND->INIT->030" "Not creating a custom build for the project, as no template was specified."
  else

    if [ -d "${path_data}" ] && [ ! -d "${path_data}/builds/${project_image}" ]; then

      command_include "build"

      local path_build="`build_find \"${project_buildtemplate}\"`"
      if [ "${path_build}" != "" ]; then
        path_ensure --dir "${path_data}/builds"
        cp -R "${path_build}" "${path_data}/builds/${project_image}"
        debug --level 5 --topic "HOOK->COMMAND->INIT->030" "Created custom build [${path_build} => ${path_data}/builds/${project_image}]"
      else
        debug --level 6 --topic "HOOK->COMMAND->INIT->030" "no matching custom build found [build:${project_build}][image:${project_image}][version:${project_imageversion}]"
      fi

    else

      debug --level 6 --topic "HOOK->COMMAND->INIT->030" "Custom build found in project folder [build:${project_build}][image:${project_image}][version:${project_imageversion}]"
      return 0

    fi

  fi
}
