#!/bin/sh
#
# INIT:HOOK: POssible include the wwwserver library as a dependency
#

hook_version=2
hook_root="hook_flow_init_090"

# descriptoin method
hook_flow_init_090_description()
{
  echo "Include the wwwserver library if told to do so"
}

# help method
hook_flow_init_090_help()
{
  echo "
hook->init->090 : Include the wwwserver library if told to do so

This hooks wil include the wwwserver library during init, where it can
then make the default library a dependency for the project

  [-s|--wwwserver] : include the wwwserver as a dependency; this will allow
     that library to affect the project through default dependencies.
"

}

# execute method
hook_flow_init_090_execute()
{
  # used only for the init flow, to tell hooks that it is ok to build things
  build_execute_now=-1

  local flags=""
  while [ $# -gt 0 ]
  do
    case "$1" in
      -s|--wwwserver)
        if ! library_loaded "wwwservercnpm"; then
          debug --level 5 --topic "HOOK->FLOW->INIT->090 Loading the wwwserver library as directed by command line arguments."
          library_load "wwwservercnpm"
        fi
        ;;
    esac
    shift
  done

}
