#!/bin/sh

#######################################
# some timing and debug related stuff #
#######################################

# Execution date & time (mainly used for logging)
date="`date +%F/%H:%m.%S`"
# Unique identifer of execution (random number)
#executionid="`echo ${date} | md5sum`"
executionid="${RANDOM}"

##################
# Common control #
##################

vflag=off
# DEBUG : default debugging level (3 gives some minimal output)
debug=${debug:-3}
# DEBUG : Logging level (same as debug, but for the log file)
log=${log:-0}

#####################
# Some reused paths #
#####################
#
# Feel free to change any of these paths
# but note that a lot of other paths may
# de based on them
#

# path executed from
path_execution="`pwd`"
# path to this management system
path_manage="$(cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd)"
# path to the root of this project, which we assume is one directory up
path_project="$(dirname ${path_manage})"
# path to user home folder (in case)
path_userhome="${HOME}"
# path to a folder where the system can keep some data
path_data="${path_project}/project"

# Include utility functions
source ${path_manage}/_utilities
# Include library handling functions
source ${path_manage}/_libraries

debug --level 7 --topic "CONFIG" "INCLUDING LIBRARIES"

# include utility functions for running hooks
library_include hook
# include command related functions
library_include command
# include help related functions (not debug, which is in utilities to get it loaded early.)
library_include help
# include docker functions - bash abstractions for docker operations
library_include docker
# include the settings library
library_include settings

debug --level 7 --topic "CONFIG" "INCLUDING LIBRARIES COMPLETE"
