#!/bin/sh
#
# Library handling
#

# register a library with the system
# @NOTE don't use this, as all it does is rememeber the path
_libraries_addlibrary()
{
  list_add "libraries_loaded" "${1}"
}
# add the core manage folder as a library, even though it isn't really a library
# this just makes some things easier
_libraries_addlibrary "core:${path_library}"

# retrieve the list of loaded libraries
libraries_list()
{
  list_get "libraries_loaded"
}
# get the list record for a specific library from the loaded list
libraries_list_get()
{
  local target="${1}"

  local library=""
  for library in `libraries_list`; do
    if [ "${target}" == "${library%:*}" ]; then
      echo "${library}"
      return 0
    fi
  done
  return 1
}

# library path retrieval
# @NOTE you can pass in the name of the library, or the library list record
library_path()
{
  local library="${1}"

  if [ "${library}" == "${library%/*}" ]; then
    library="`libraries_list_get \"${library}\"`"
    if [ $? -gt 0 ]; then
      return 1
    fi
  fi

  echo "${library##*:}"
}
# library handler retrieval
# @NOTE you can pass in the name of the library, or the library list record
library_handler()
{
  local library="${1}"

  if [ "${library}" == "${library%/*}" ]; then
    library="`libraries_list_get \"${library}\"`"
    if [ $? -gt 0 ]; then
      return 1
    fi
  fi

  local handler="${library##*/}"
  handler="${handler/./}"
  echo "${library##*:}/${handler}"
}

# list all contents of a subpath in any library
# @NOTE this is used for components and hooks, which can exist in
#       any library.
libraries_contents()
{
  local subpath=""
  local type="exec"

  while [ $# -gt 0 ]
  do
    case "$1" in
      -d|--dir|--directory)
        type="dir"
        ;;
      -f|--file)
        type="file"
        ;;
      -l|--library)
        type="library"
        ;;
      -x|--executable)
        type="exec"
        ;;
      -s|--subpath)
        subpath="/${2}"
        shift
        ;;
      -t|--type)
        type="${2}"
        shift
        ;;
      *)
        break;
    esac
    shift
  done

  local library=""
  for library in `libraries_list`; do
    path_contents --type "${type}" "`library_path \"${library}\"`${subpath}"
  done
}

# boolean responder for if a library is loaded
# returns 0 for loaded, 1 for not loaded
library_loaded()
{
  local library=""
  for library in `libraries_list`; do
    case " ${library} " in
      *" ${1}:"*)
          debug --level 9 --topic "LIBRARY->LOADED" "library is already loaded [library:${library}]"
          return 0
        ;;
    esac
  done

  debug --level 9 --topic "LIBRARY->LOADED" "library is NOT already loaded [library:${library}]"
  return 1
}

# this is a safe hooks executor, for handling cases where the hooks library has not been loaded yet.
# this is necessary for the case of loading the hooks library, and any libraries before that.
_libraries_hooks_execute()
{
  if function_exists "hooks_execute"; then
    hooks_execute $@
  fi
}

# public handler for loading a library
library_load()
{
  local library=""
  local component=""
  local path=""
  local subpath=""

  while [ $# -gt 0 ]
  do
    case "$1" in
      -c|--component)
        component="${2}"
        shift
        ;;
      -p|--path)
        # if a component is passed, then this path os for the component
        path="$2"
        shift
        ;;
      -s|--subpath)
        # component subpath folder (only used if --component is passed)
        subpath="$2"
        shift
        ;;
      *)
          break;; # terminate while loop
    esac
    shift
  done

  local library="${1}"
  shift

  local success=-1

  if library_loaded "${library}"; then
    # library is already loaded
    debug --level 7 --topic "LIBRARY->LOAD" "library already loaded [library:${library}]"
    success=0
  else

    if [ -z "${component}" ] && [ -n "${path}" ]; then

      if path_is --library "${path}"; then
        _library_load --library "${library}" --path "${path}" $@
        success=$?
        if [ $success -eq 0 ]; then
          debug --level 7 --topic "LIBRARY->LOAD" "suggested path library loaded [library:${library}][path:${path}][success:${success}]"
        else
          debug --level 7 --topic "LIBRARY->LOAD" "suggested path library load failed [library:${library}][path:${path}][success:${success}]"
        fi
      else
        success=1
        debug --level 6 --topic "LIBRARY->LOAD" "suggested path for library not found, or not a library [library:${library}][path:${path}][success:${success}]"
      fi

    else

      local library_each=""
      for library_each in `libraries_list`
      do
        path="`library_path "${library_each}"`/libraries/${library}"

        if path_is --library "${path}"; then
          debug --level 8 --topic "LIBRARY->LOAD" "library exists [library:${library}][path:${path}][success:${success}]"
          _library_load --library "${library}" --path "${path}" $@
          success=$?
          if [ $success -eq 0 ]; then
            debug --level 7 --topic "LIBRARY->LOAD" "library found and loaded [library:${library}][path:${path}][success:${success}]"
          else
            debug --level 6 --topic "LIBRARY->LOAD" "library found but load failed [library:${library}][path:${path}][success:${success}]"
          fi

          break
        else
          success=1
          debug --level 8 --topic "LIBRARY->LOAD" "library path does not exist [library:${library}][path:${path}][success:${success}]"
        fi
      done

      if [ $success -lt 0 ]; then
        debug --level 6 --topic "LIBRARY->LOAD" "library could not be found [library:${library}][path:${path}][success:${success}]"
        success=1
      fi

    fi

  fi

  # handle component if library is now loaded, and a component was requested
  if [ $success -eq 0 ] && [ -n "${component}" ]; then

    if [ -n "${path}" ]; then

      if path_is --type "library" "${path}"; then
        _library_load --library "${component}" --path "${path}"
        local success=$?
        if [ $success -eq 0 ]; then
          debug --level 7 --topic "LIBRARIES->COMPONENT->LOAD" "Library component loaded [library:${library}][component:${component}]"
        else
          debug --level 6 --topic "LIBRARIES->COMPONENT->LOAD" "Library component loading failed [library:${library}][component:${component}][success:${success}]"
        fi
        return $success
      else
        debug --level 5 --topic "LIBRARIES->COMPONENT->LOAD" "Library component could not be found, it does not exists or was not a library [library:${library}][component:${component}][given path:${path}]"
        return 1
      fi
    else
      # if no subpath was passed in, the fake a plural of the library name
      if [ -z "${subpath}" ]; then
        subpath="${library}s"
      fi

      local this_library=""
      for this_library in `libraries_list`; do
        path="`library_path \"${this_library}\"`/${subpath}/${component}"
        if path_is --type "library" "${path}"; then
          _library_load --library "${component}" --path "${path}"
          success=$?
          if [ $success -eq 0 ]; then
            debug --level 7 --topic "LIBRARIES->COMPONENT->LOAD" "Library component loaded [library:${library}][component:${component}][in library:${this_library}]"
          else
            debug --level 6 --topic "LIBRARIES->COMPONENT->LOAD" "Library component loading failed [library:${library}][component:${component}][in library:${this_library}]"
          fi
          return $success
        fi
      done

      debug --level 5 --topic "LIBRARIES->COMPONENT->LOAD" "Library component could not be found [library:${library}][component:${component}]"
      return 1
    fi

  fi

  return $success
}
# internal handler for actually loading a library
#
# -l|--library {library} : the library name, which is used to track loading
# -p|--path {path} : path to the library (folder, in for a simple library, the executable file)
# [-f|--corefile {corefile}] : optional alternative core file for a folder library
#
# @NOTE this doesn't care if it is a library, component
#       but it is responsible for checking if it is a
#       simple or directory library, loading the core
_library_load()
{
  local library=""
  local path=""

  while [ $# -gt 0 ]
  do
    case "$1" in
      -l|--library)
        library="$2"
        shift
        ;;
      -p|--path)
        path="$2"
        shift
        ;;
      *)
          break;; # terminate while loop
    esac
    shift
  done

  if path_is --library "${path}"; then
    local path_include="${path}"

    if path_is --dir "${path}"; then
      debug --level 8 --topic "LIBRARY->_LOAD" "library is a directory based lib [library:${library}][path:${path}]"
      path_include="`library_handler "${library}:${path}"`"
    else
      debug --level 8 --topic "LIBRARY->_LOAD" "library is a simple library (this library can't have components or includes.) [path:${path}]"
    fi

    debug --level 8 --topic "LIBRARY->_LOAD" "Now loading library [library:${library}][path:${path}]"


    debug --level 7 --topic "LIBRARY->_LOAD" "Including library root.  Handing off to path_include ==> path_include \"${path_include}\" $@ "
    if path_include "${path_include}" $@; then
      # register the library as a path
      list_add "libraries_loaded" "${library}:${path}"

      # run pre hooks
      _libraries_hooks_execute "library/load" --state "pre" --library "${library}" --path "${path}" $@

      if _library_execute --action "init" "${library}" --path "${path}"; then
        debug --level 7 --topic "LIBRARY->LOAD" "Library init function run"
      fi

      # run post hooks
      _libraries_hooks_execute "library/load" --state "post" --library "${library}" --path "${path}" $@

      debug --level 6 --topic "LIBRARY->_LOAD" "library loaded [library:${library}][path:${path}]"
      return 0
    else
      debug --level 6 --topic "LIBRARY->_LOAD" "library load failed  [library:${library}][path:${path}][success:${success}]"
      # run fail hooks
      _libraries_hooks_execute "library/load" --state "fail" --library ${library} --path ${path} $@
      return 1
    fi

  fi

  debug --level 7 --topic "LIBRARY->_LOAD" "library root does not exist, or is not executable, it cannot be loaded [library:${library}][path:${path}]"
  return 1
}
# Include a file in a library root
library_include()
{
  # empty defaults
  local library=""
  local component=""
  local include=""
  local subpath=""

  while [ $# -gt 0 ]
  do
    case "$1" in
      -c|--component)
        component="$2"
        shift
        ;;
      -s|--subpath)
        subpath="$2"
        shift
        ;;
      *)
          break;; # terminate while loop
    esac
    shift
  done

  # library is the first thing loaded, include is the second
  local library="$1"
  local include="$2"
  shift 2

  local path=""
  if [ -z "${component}" ]; then
    library_load "${library}"
    library="`libraries_list_get \"${library}\"`"
    path="`library_path \"${library}\"`"
  else
    library_load --component "${component}" "${library}"
    library="`libraries_list_get \"${component}\"`"
    path="`library_path \"${library}\"`"
  fi

  path="${path}/${subpath}${include}"
  debug --level 5 --topic "LIBRARY->INCLUDE" "Including library component file [library:${library%:*}][component:${component}][path:${path}] : $@"
  path_include "${path}"
  return $?
}

# Execute a library handler function
# @NOTE this function tries to make sure that the library is loaded
#       and it is component aware.
library_execute()
{
  # empty defaults
  local library=""
  local component=""
  local action="execute"

  while [ $# -gt 0 ]
  do
    case "$1" in
      -a|--action)
        action="$2"
        shift
        ;;
      -c|--component)
        component="$2"
        shift
        ;;
      *)
          break;; # terminate while loop
    esac
    shift
  done

  # library is the first thing loaded
  local library=$1
  shift

  # include the library
  if [ -z "${component}" ]; then
    library_load "${library}" $@
    success=$?
    if [ $success -eq 0 ]; then
      _library_execute --action "${action}" "${library}" $@
    else
      debug --level 4 --topic "LIBRARY->EXECUTE" "library execute was not given a valid library name [library:${library}][action:${action}][function:${library_function}]"
      return 1
    fi
  else
    library_load --component "${component}" "${library}" $@
    success=$?
    if [ $success -eq 0 ]; then
      _library_execute --component "${component}" --action "${action}" "${library}" $@
    fi
  fi

  return $?
}
# Execute internal handler
# @NOTE this is used in the _libraries handler for cases where we don't need
#       to worry about loading the library, or handling components.
_library_execute()
{
  # empty defaults
  local library=""
  local component=""
  local action="execute"

  while [ $# -gt 0 ]
  do
    case "$1" in
      -a|--action)
        action=$2
        shift
        ;;
      -c|--component)
        component=$2
        shift
        ;;
      *)
          break;; # terminate while loop
    esac
    shift
  done

  # library is the first thing loaded
  local library=$1
  shift

  if [ -z "${library}" ]; then
    debug --level 2 --topic "LIBRARY->_EXECUTE" "library execute was not given any library name [library:${library}][action:${action}][function:${library_function}]"
    return 1
  fi

  # generate a safe function name for the library/component method
  if [ -z "${component}" ]; then
    local library_function="${library//-/_}_${action}"
  else
    local library_function="${component//-/_}_${action}"
    debug --level 8 --topic "LIBRARY->_EXECUTE" "library execute is for a component [library:${library}][action:${action}][function:${library_function}]"
  fi

  function_exists "${library_function}"
  if [ $? -eq 0 ]; then
    debug --level 8 --topic "LIBRARY->_EXECUTE" "Handing off to library function [library:${library}][action:${action}] : ${library_function} $@"
    eval ${library_function} $@
    success=$?
    if [ $success -eq 0 ]; then
      debug --level 7 --topic "LIBRARY->_EXECUTE" "Library execute succeeded [library:${library}][action:${action}]."
    else
      debug --level 5 --topic "LIBRARY->_EXECUTE" "Command execution failed for library, command method returned an error [library:${library}][component:${component}][action:${action}][success:${success}]"
    fi
    return $sucess
  else
    debug --level 7 --topic "LIBRARY->_EXECUTE" "Library execute method was not found in the library [library:${library}][action:${action}]."
    return 1
  fi
}
