#!/bin/sh
#
# Workflow based docker container management
#

############################
# Process config Arguments #
############################
# -v|--verbose {level} : output debugging info
# -l|--log {level} : enable debug logging
# -f|--force : ignore critical errors (don't halt)
#
# @TODO find a way past the described silliness

help=0

while [ $# -gt 0 ]
do
  case "$1" in
    -h|--help)
      help=1
      ;;

    -v|--verbose)
      vflag=on
      # if an integer level was passed, take it, otherwise default to 5
      if [ -n "$2" ] && [ -z "${2##[0-9]}" ]; then
        debug=${2}
        shift
      else
        debug=5
      fi
      ;;
    -l|--log)
      # if an integer level was passed, take it, otherwise default to 8
      if [ -n "$2" ] && [ -z "${2##[0-9]}" ]; then
        log=${2}
        shift
      else
        log=8
      fi
      ;;
    -f|--force)
      # lower the critical error level so that errors don't halt
      _debug_critical_level=0
      ;;
    -*)
        echo >&2 "usage: $0 [-v|--verbose] [-l|--log [{log level}]]  [flow ...].  Try \"help\" for more instructions."
        exit 1;;
    *)
        break;; # terminate while loop
  esac
  shift
done

#####################################################
# Find out where we are, and connect to the _config #
#####################################################

# path to the root of this project
path_script="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd)"
# include _config, which will do the rest of the work.
source "${path_script}/_config"

##########################$######################
# Determine what workflow is supposed to be run #
###########################$#####################
# the first non-hyphenated argument is the flow
WORKFLOW=$1
shift

# Maybe print some debug info (debug command loses carriage returns, so we echo ourselves)
  # Maybe print some debug info (debug command loses carriage returns, so we echo ourselves)
if [ $debug -gt 3 ]; then
  if [ $help -gt 0 ]; then
    echo "
WORKFLOW: final control settings: [
  >HELP MODE ENABLED
  >WORKFLOW TO BE HELPED WITH
  -->workflow:${WORKFLOW}
  -->Args:${@}
]"
  else
    echo "
WORKFLOW: final control settings: [
  >WORKFLOW TO BE EXECUTED
  -->workflow:${WORKFLOW}
  -->Args:${@}
]"
  fi
fi

####################################################################
# Process workflow : pass the rest of the arguments to the flow #
####################################################################

if [ $help -gt 0 ]; then

  # execute any existing pre hooks
  debug --level 7 --topic "WORKFLOW" "Running flow:help hooks => hooks_execute \"flow/help}\" --state \"help\" ${WORKFLOW} $@"
  hooks_execute "flow" --state "help"  ${WORKFLOW} $@
  success=$?


else

  # execute any existing pre hooks
  debug --level 7 --topic "WORKFLOW" "Running flow:pre hooks => hooks_execute \"flow/${WORKFLOW}\" --state \"pre\" $@"
  hooks_execute "flow/${WORKFLOW}" --state "pre" $@

  # execute any existing pre hooks
  debug --level 7 --topic "WORKFLOW" "Running flow:pre hooks => hooks_execute \"flow/${WORKFLOW}\" --state \"pre\" $@"
  hooks_execute "flow/${WORKFLOW}" $@

  # execute any existing pre hooks
  debug --level 7 --topic "WORKFLOW" "Running flow:post hooks => hooks_execute \"flow/${WORKFLOW}\" --state \"post\" $@"
  hooks_execute "flow/${WORKFLOW}" --state "post" $@

fi
