#!/bin/sh
#
# Workflow based docker container management
#

############################
# Process config Arguments #
############################
# -h|--help {topic} : run help instead of the workflow
# -v|--verbose {level} : output debugging info
# -l|--log {level} : enable debug logging
# -f|--force : ignore critical errors (don't halt)
#
# @TODO find a way past the described silliness

help="no"
helptopic=""

while [ $# -gt 0 ]
do
  case "$1" in
    -h|--help)
      # if an string with a colon (topic separator) was passed, take it as the help topic
      if [ -n "$2" ] && [ "$2" != "${2##*:}" ]; then
        helptopic=${2}
        shift
      fi
      help="yes"
      ;;

    -v|--verbose)
      vflag=on
      # if an integer level was passed, take it, otherwise default to 5
      if [ -n "$2" ] && [ -z "${2##[0-9]}" ]; then
        debug=${2}
        shift
      else
        debug=5
      fi
      ;;
    -l|--log)
      # if an integer level was passed, take it, otherwise default to 8
      if [ -n "$2" ] && [ -z "${2##[0-9]}" ]; then
        log=${2}
        shift
      else
        log=8
      fi
      ;;
    -f|--force)
      # lower the critical error level so that errors don't halt
      _debug_critical_level=0
      ;;
    -*)
        echo >&2 "usage: $0 [-v|--verbose] [-l|--log [{log level}]]  [flow ...].  Try \"help\" for more instructions."
        exit 1;;
    *)
        break;; # terminate while loop
  esac
  shift
done

#####################################################
# Find out where we are, and connect to the _config #
#####################################################

# path to the root of this project
path_script="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd)"
# include _config, which will do the rest of the work.
source "${path_script}/_init"

# include the flow library
library_include flow

#################################################
# Determine what workflow is supposed to be run #
#################################################
# the first non-hyphenated argument is the flow
WORKFLOW=$1
shift

# Maybe print some debug info (debug command loses carriage returns, so we echo ourselves)
  # Maybe print some debug info (debug command loses carriage returns, so we echo ourselves)
if [ $debug -gt 3 ]; then
  if [ $help == "yes" ]; then
    echo "
WORKFLOW: final control settings: [
  >HELP MODE ENABLED
  >WORKFLOW TO BE HELPED WITH
  -->workflow:${WORKFLOW}
  -->Args:${@}
]"
  else
    echo "
WORKFLOW: final control settings: [
  >WORKFLOW TO BE EXECUTED
  -->workflow:${WORKFLOW}
  -->Args:${@}
]"
  fi
fi

####################################################################
# Process workflow : pass the rest of the arguments to the flow #
####################################################################

if [ "$help" == "yes" ]; then

  debug --level 5 --topic "WORKFLOW" "Running flow:help hooks => help_execute \"flow\" ${WORKFLOW}\" $@"
  help_execute "flow" ${WORKFLOW} $@

  if [ -n "${helptopic}" ]; then
    # run the help handler for whatever help topic was passed in
    debug --level 5 --topic "COMMAND" "Running help hooks for help topic =>help_execute \"${helptopic%:*}\" \"${helptopic##*:}\" $@"
    help_execute "${helptopic%:*}" "${helptopic##*:}" $@
  fi

else

  # execute any existing pre hooks
  debug --level 7 --topic "WORKFLOW" "Running flow:pre hooks => hooks_execute \"flow/${WORKFLOW}\" --state \"pre\" $@"
  hooks_execute "flow/${WORKFLOW}" --state "pre" $@

  # execute any existing pre hooks
  debug --level 7 --topic "WORKFLOW" "Running flow:pre hooks => hooks_execute \"flow/${WORKFLOW}\" --state \"pre\" $@"
  hooks_execute "flow/${WORKFLOW}" $@
  success=$?

  if [ $success -eq 0 ]; then
    # execute any existing post hooks
    debug --level 7 --topic "WORKFLOW" "Running flow:post hooks => hooks_execute \"flow/${WORKFLOW}\" --state \"post\" $@"
    hooks_execute "flow/${WORKFLOW}" --state "post" $@
  else
    # execute any existing fail hooks
    debug --level 7 --topic "WORKFLOW" "Running flow:fail hooks => hooks_execute \"flow/${WORKFLOW}\" --state \"faile\" $@"
    hooks_execute "flow/${WORKFLOW}" --state "fail" $@
  fi
  exit $success

fi
