#!/bin/sh
#
# 500 Show help for failed command
#

hook_version=2
hook_root="hook_command_fail_500"

# description method
hook_command_fail_500_description()
{
  echo "Show help for a command, if it fails to execute"
}

# help method
hook_command_fail_500_help()
{
  echo "
HOOK->COMMAND->FAIL->500 Show help for a command if it failes to execute

Run the help process for a command, if it fails to execute.

@NOTE this handles unknown commands.
"
}

# execute method
hook_command_fail_500_execute()
{
  echo "

There was a problem executing your command. The command failed.

"
  hooks_execute "command" --state "help" $@

}
