#!/bin/sh
#
# HOOK->FLOW->STATUS->100 Status flow help
#

hook_version=2
hook_root="hook_flow_status_100"

# description method
hook_flow_status_100_description()
{
  echo "Status flow help"
}

# help method
hook_flow_status_100_help()
{
 echo "HOOK->FLOW->STATUS->100 Status flow help

If directed by status flow topics, output help for the
status flow.
This is just a shortcut to get help in the use of the
flow.

@NOTE this topic is the only one that does not respond
  to the \"all\" topic.
"
}

# execute method
hook_flow_status_100_execute()
{
  case " ${flow_status_topics} " in
    # Could not decide what behaviour to use
    #*" all "*|*" help "*)
    *" help "*)
      echo "
STATUS HELP
==========="
      help_execute "flow:status"
      ;;
  esac
}
