#!/bin/sh
#
# HOOK->FLOW->STATUS->200 Status flow help
#

hook_version=2
hook_root="hook_flow_status_200"

# description method
hook_flow_status_200_description()
{
  echo "Status flow help"
}

# help method
hook_flow_status_200_help()
{
 echo "HOOK->FLOW->STATUS->200 Status flow help
"
}

# execute method
hook_flow_status_200_execute()
{
  case " ${flow_status_topics} " in
    *" all "*|*" settings "*)
      echo "
PROJECT SETTINGS
================
control settings used in this state: [
  >SINGLE PATHS USED
  -->path_project----------: ${path_project}
  -->path_execution--------: ${path_execution}
  -->path_library----------: ${path_library}
  >CONFS
  -->path_userconf---------: ${path_userconf}
  -->path_projectconf------: ${path_projectconf}
  >ALIASES
  -->active_aliases--------: `aliases_get`
  >LIBRARIES
  -->libraries loaded------: `libraries_list`
  >HOOKS
  -->path_hooks------------: `hooks_getpath`
  >PROJECT CONFIGURATION
  -->Project_name----------: ${project_name}
  >PROJECT DOCKER CONFIGURATIONS
  -->project_container-----: ${project_container}
  -->project_image---------: ${project_image}
  -->project_imageversion--: ${project_imageversion}
  >PROJECT MACHINE CONFIGURATIONS
  -->Machine_hostname------: ${machine_hostname}
  -->Machine_mountvolumes--: `settings_mount_getmounts --short`
  -->Machine_shell---------: ${machine_shell}
  -->Machine_shellrunargs--: ${machine_shellrunargs}
  -->Machine_runargs-------: ${machine_runargs}
]"
      ;;
  esac
}
