#!/bin/sh
#
# HOOK->FLOW->STATUS->300 Project builds
#

hook_version=2
hook_root="hook_flow_status_300"

# description method
hook_flow_status_300_description()
{
  echo "Analyze builds used in the project"
}

# help method
hook_flow_status_300_help()
{
 echo "HOOK->FLOW->STATUS->300 Project builds
"
}

# execute method
hook_flow_status_300_execute()
{

  local build="${project_build}"

  local flags=""
  while [ $# -gt 0 ]
  do
    case "$1" in
      -i|--build)
        build="$2"
        shift
        ;;
    esac
    shift
  done

  library_load "command"
  command_load "build"

  echo "
Project builds
=============="

  if [ "${build}" == "" ]; then
    echo "no project build specified, the project_build variable is empty"
  else
    echo "-->project_build:${project_build}"
    local path="`build_find $build`"
    if [ -d "${path}" ]; then
      echo "-->build found in path: ${path}"
    else
      echo "
Build not found in the system
"
    fi
  fi
}
