#!/bin/sh
#
# HOOK->FLOW->STATUS->300 Project builds
#

hook_version=2
hook_root="hook_flow_status_300"

# description method
hook_flow_status_300_description()
{
  echo "Analyze builds used in the project"
}

# help method
hook_flow_status_300_help()
{
 echo "HOOK->FLOW->STATUS->300 Project builds

If directed to do so by status topics, display a information about
the project build on screen.
Builds are folders that container a Dockerfile, and various other
contents, used by Docker to build an image.
"
  help_scope_add "docker:docker_build"
  help_scope_list
}

# execute method
hook_flow_status_300_execute()
{
  case " ${flow_status_topics} " in
    *" all "*|*" build "*)

      library_load "command"
      command_load "build"

      echo "
PROJECT BUILDS
=============="

      if [ "${project_build}" == "" ]; then
        echo "no project build specified, the project_build variable is empty"
      else
        echo "-->project_build:${project_build}"
        local path="`build_find "${project_build}"`"
        if [ -d "${path}" ]; then
          echo "-->build found in path: ${path}"
        else
          echo "Build not found in the system"
        fi
      fi

      ;;
  esac
}
