#!/bin/sh
#
# HOOK->FLOW->STATUS->310 Project images
#

hook_version=2
hook_root="hook_flow_status_310"

# description method
hook_flow_status_310_description()
{
  echo "Analyze images used in the project"
}

# help method
hook_flow_status_310_help()
{
 echo "HOOK->FLOW->STATUS->310 Project images

If directed to by the status flow topics, this hooks will output
information about the active image in the system.  It will show
the docker image information, if the image exists.
"
}

# execute method
hook_flow_status_310_execute()
{
  case " ${flow_status_topics} " in
    *" all "*|*" image "*)

      echo "
PROJECT IMAGES
==============
-->project_image: ${project_image}"

      if [ "${project_image}" == "" ]; then
        echo "there is no image specfied for this project"
      else
        if docker_image_exists ${project_image}; then
          echo "Occurences of related image in this system:
REPOSITORY                        TAG                 IMAGE ID            CREATED             VIRTUAL SIZE"
          docker_inspect_image_list --image "${project_image}"
        else
          echo "No matching images found [image:${project_image}]"
        fi
      fi

      ;;
  esac
}
