#!/bin/sh
#
# HOOK->FLOW->STATUS->320 Project containers
#

hook_version=2
hook_root="hook_flow_status_320"

# description method
hook_flow_status_320_description()
{
  echo "Analyze containers used in the project"
}

# help method
hook_flow_status_320_help()
{
 echo "HOOK->FLOW->STATUS->320 Project containers

Attempt to output information about the active container in the project.
"
}

# execute method
hook_flow_status_320_execute()
{
  case " ${flow_status_topics} " in
    *" all "*|*" cont.*all "*|*" cont.active "*)

      echo "
ACTIVE CONTAINER
================"

      if [ "${project_container}" == "" ]; then
        echo "there is no container specfied for this project"
      else
        if docker_container_exists ${project_container}; then
          echo "
Primary project container:
-->project_container: ${project_container}  IP:`docker_inspect_getIP --container \"${project_container}\"`
CONTAINER ID        IMAGE               COMMAND             CREATED             STATUS              PORTS               NAMES"
          docker_inspect_container_list --name "${project_container}"
        else
          echo "No matching containers found [container:${project_container}]"
        fi
      fi

      ;;
   esac

}
