#!/bin/sh
#
# Default settings for the www-deblamp-mz library
#

# This library has a default template that can be used in the system for new project builds
# @NOTE this settings is only really used for the init flow
project_buildtemplate="${project_buildtemplate:-www-deblamp-mz}"
