#!/bin/sh
#
# Feature Library hander
#


# feature load
feature_load()
{
  local feature="${1}"

  debug --level 8 --topic "FEATURE->LOAD" "Loading feature [feature:${feature}]"

  # execute any feature load pre hooks
  hooks_execute --state "pre" "feature/load"

  library_load --component "${feature}" "feature"
  local success=$?
  if [ $success -eq 0 ]; then
    # execute any feature load pre hooks
    hooks_execute --state "post" "feature/load"

    debug --level 5 --topic "FEATURE->LOAD" "Loading feature succeed [feature:${feature}]"
    message "Using feature: ${feature}"
  else
    # execute any feature load pre hooks
    hooks_execute --state "fail" "feature/load"

    debug --level 5 --topic "FEATURE->LOAD" "Loading feature failed [feature:${feature}]"
    message "Failed to find feature ${feature}, using defaults instead"
  fi
}
