#!/bin/sh
#
# Feature Library hander
#

feature_path()
{
  echo "${path_features}/${1}"
}

# Boch handler
feature_execute()
{
  local action="${1}"
  shift

  if [ -n "${action}" ]; then
    local flow="feature/${action}"

    # make sure that we have loaded the flow library
    library_load "flow"

    if flow_exists "${flow}"; then

      library_execute "flow" "${flow}" $@
      return $?

    else

      library_execute "help" "feature:${action}" $@

    fi

  else

    library_execute "help" "feature:general" $@

  fi

}

# feature load
feature_load()
{
  local feature="${1}"
  shift
  debug --level 8 --topic "FEATURE->LOAD" "Loading feature [feature:${feature}]"

  # execute any feature load pre hooks
  hooks_execute "feature/load" --state "pre" --feature "${feature}" $@

  library_load --component "${feature}" "feature"
  local success=$?
  if [ $success -eq 0 ]; then
    # execute any feature load pre hooks
    hooks_execute "feature/load"--state "post" --feature "${feature}" $@

    debug --level 5 --topic "FEATURE->LOAD" "Loading feature succeed [feature:${feature}]"
    message "Using feature library: ${feature}"
  else
    # execute any feature load fail hooks
    hooks_execute "feature/load" --state "fail" --feature "${feature}" $@

    debug --level 5 --topic "FEATURE->LOAD" "Loading feature failed [feature:${feature}]"
    message "Failed to find feature ${feature}, using defaults instead"
    return 1
  fi
  return 0
}

# create a feature library
feature_create()
{
  local path="${path_features}"

  local flags=""
  while [ $# -gt 0 ]
  do
    case "$1" in
      -p|--path)
        path="${2}"
        shift
        ;;
      *)
        break;
    esac
    shift
  done

  local name="${1}"
  shift

  if [ -n "${name}" ]; then
    if path_ensure --dir "${path}"; then
      library_create --complex --path "${path}" "${name}" $@
      if [ $? -eq 0 ]; then
        debug --level 7 --topic "HOOK->FEATURE->CREATE->PRE->400" "Created feature library [name:${name}][path:${path}]"
      else
        debug --level 7 --topic "HOOK->FEATURE->CREATE->PRE->400" "Failed to create feature library [name:${name}][path:${path}]"
        return 1
      fi
    else
      debug --level 7 --topic "HOOK->FEATURE->CREATE->PRE->400" "Failed to create feature library because the path does not exist [name:${name}][path:${path}]"
      return 1
    fi
  fi
}

# List all of the features in the system
features_list()
{
  local path=""
  for path in `libraries_contents --library --subpath "features"`; do
    echo "${path##*/}:${path}"
  done
}
