#!/bin/sh
#
# help handler for the feature library
#

# help
feature_help()
{
  if [ -z "${1}" ]; then
    feature_help_generalhelp

    help_scope_add "feature:general"
    help_scope_list
  else

    case "${1}" in
      "create")
        feature_help_create
        ;;
      *)
        feature_help_unknowntopic
        ;;
    esac
  fi
}

# help-list
feature_helplist()
{
  if [ -z "${1}" ]; then
    echo "Feature help topics
--> create : Create a new feature (feature:create)
"
  else
    echo "no help topics"
  fi
}

# general help message
feature_help_generalhelp()
{
  echo "FEATURE General help

The feature library is just magnificent
"
}

feature_help_unknowntopic()
{
  echo "Unknown feature topic

You tried to use an unknown feature topic or command

"
}

feature_help_create()
{
  echo "Feature: Create help

How to create a feature

"
}
