#!/bin/sh
#
# HOOK->HELP->HELP->050 Help handler for the help library
#

hook_version=2
hook_root="hook_help_help_050"

# description method
hook_help_help_050_description()
{
  echo "Help handler hook for the help library"
}

# help method
hook_help_help_050_help()
{
  echo "
HOOK->HELP->HELP->050 Help handler for the help library

All Libraries can have a help handler hook, that can receive help requests
to any target that uses the library.

In this case, this handler handles any help topic of the form \"help:{sub-topic}\"

Note that this hook doesn't handle any other topics.  It is used for general
help if no topic is specified.
"
}

# execute method
hook_help_help_050_execute()
{
  local topic="$1"
  case "${topic}" in
    init)
      hook_help_help_050_topic_init
      ;;
    hooks)
      hook_help_help_050_topic_hooks
      ;;
    project)
      hook_help_help_050_topic_project
      ;;
    libraries)
      hook_help_help_050_topic_libraries
      ;;
    *)
      if [ -n "${topic}" ]; then
        hook_help_help_050_help_unknowntopic "${topic}" $@
      fi

      hook_help_help_050_help_general
    ;;
  esac

}

# list help topics method
hook_help_help_050_list()
{
  echo "SYSTEM HELP TOPICS
--> System initialization (help:init)
--> Libraries (help:libraries)
--> Hooks (help:hooks)
--> The project folder (help:project)
"
  echo "LIBRARIES THAT SHOULD HAVE HELP TOPICS:"
  local library=""
  for library in `libraries_list`; do
    if [ "${library%:*}" != "help" ]; then
      echo "--> ${library%:*} (${library%:*}:general)"
    fi
  done
}


hook_help_help_050_help_general()
{
 echo "HOOK->HELP->HELP->050 This is the generic help handler for the toolset

- give a description on how the system works
- explain that there are two primary scripts (control and flow)

- explain what help topic are
  - explain that help topics have a semicolon separator
  - give some examples of hooks
  - explain that the {topic}:general topic has a specific purpose
  - explain that a list of system help topics will be listed below

- explain that help topics are library specific
  - explain that a list of libraries follows
  - warn that this list of libraries depends on what libraries are
    currently loaded.
"

  help_scope_add "help"

  help_scope_list
}

# Unknow topic message
hook_help_help_050_help_unknowntopic()
{
  topic="$1"

 echo "HOOK->HELP->HELP->050 UNKNOWN TOPIC MESSAGE

Could not find any help for your topic: ${topic}

"
}

hook_help_help_050_topic_init()
{
 echo "HOOK->HELP->HELP->050 Help topic handler for system initialization

- explain how init works
- explain what the _init script is
"
}

hook_help_help_050_topic_libraries()
{
 echo "HOOK->HELP->HELP->050 Help topic handler for libraries

- explain what libraries are
- discuss what libraries can container
- explain how libraries are included

- suggest including a library in your project folder
"
}

hook_help_help_050_topic_hooks()
{
 echo "HOOK->HELP->HELP->050 Help topic handler for hooks

- shortly explain hooks
- suggest looking for help on topic hook:
"
}

hook_help_help_050_topic_project()
{
 echo "HOOK->HELP->HELP->050 Help topic handler for the project folder

- explain that the project folder is for your project
- explain that the project folder is a library
  - explain how to get help on libraries
"
}
