#!/bin/sh
#
# Configurable settings for the project
#
# @todo : move some of this to yaml?

hook_version=2
hook_root="hook_settings_035"

# description method
hook_settings_035_description()
{
  echo "Load settings from loaded libraries"
}

# help method
hook_settings_035_help()
{
  echo "
hook->settings 030 : Load settings from loaded libraries

Here we will go through all of the loaded libraries and load
any ./settings file in the library root folder
"
}

# execute method
hook_settings_035_execute()
{
  local library_path=""
  local path=""
  for library_path in `libraries_list`; do
    case "${library_path%:*}" in
      "project"|"settings")
        debug --level 8 --topic "HOOKS->SETTINGS->LIBRARY->ADD->PRE->060" "Skipping libraries that are hardcoded to not use settings (the project library, and the settings library) [library:${library}][path:${path}]"
      ;;
      *)
        path="${library_path##*:}/settings"

        if [ -f "${path}" ] && [ -x "${path}" ]; then
          debug --level 6 --topic "HOOKS->SETTINGS->035" "Loaded library has a settings file.  Adding it. [library:${library%%*:}][path:${path}]"
          path_include "${path}"
        fi
      ;;
    esac
  done
}
