#!/bin/sh
#
# Configurable settings for the project
#

hook_version=2
hook_root="hook_settings_400"

# description method
hook_settings_400_description()
{
  echo "Load the custom user boch folder as a library"
}

# help method
hook_settings_400_help()
{
  echo "
hook->settings->400 : include a user boch folder as a library

This hooks attempts to load a users .boch folder as a library,
to include any settings from the folder.
As a corrolary, any library load action is taken.

Currently there are library load hooks in the hooks library, the settings
library and the commands library, which will check for relevant folders
in the project.

"
  help_topic_add "hook:library/load"
  help_topic_list
}


# execute method
hook_settings_400_execute()
{
debug_set_level 8 "CHECK USERCONF"
  if path_is --library "${path_userconf}"; then

    library_load --path "${path_userconf}" "userconf"

    if [ $? -gt 0 ]; then
      debug --level 3 --topic "HOOK->SETTINGS->400" "Custom user boch library load produced an error [path:${path_userconf}]"
    else
      debug --level 8 --topic "HOOK->SETTINGS->400" "Loaded user boch folder as a library [path:${path_userconf}]"
    fi

  else
    debug --level 6 --topic "HOOK->SETTINGS->400" "No custom user boch folder exists [path:${path_userconf}'"
  fi
debug_reset_level
  # don't fail, even if we had problems.  This shouldn't break anything
  return 0
}
