#!/bin/sh
#
# COMMAND: Initialize the local project
#

# command help function
init_help()
{
  echo "
Initialize the local project.

This command will create various files and folders often
used by the management tools.

@NOTE used to be $/> ./flow init
"
}

# Command execute function
init_execute()
{

  local flags=""
  while [ $# -gt 0 ]
  do
    case "$1" in
      -b|--build)
        project_build="${2}"
        shift
        ;;
      -i|--image)
        project_image="${2}"
        shift
        ;;

      -h|--hostname)
        machine_hostname="${2}"
        shift
        ;;
      -n|--name)
        project_name="${2}"
        path_data="${path_project}/${2}"
        shift
        ;;
      -v|--version)
        project_version="${2}"
        shift
        ;;
      -w|--wwwserver)
        library_load wwwservercpnm
        shift
        ;;
      *)
        break;
    esac
    shift
  done

  # Run the stop function
  debug --level 5 --topic "COMMAND" "running init hooks"
  return $?
}
