#!/bin/sh
#
# Boot2Docker library help handler
#

boot2docker_help()
{
  local topic="$1"

  if [ -z "${topic}" ]; then
    boot2docker_help_general
  else
    case "${topic}" in
      "mount_vboxsf")
        boot2docker_help_topic_vboxsf
        ;;
      *)
        boot2docker_help_topicnotfound
        boot2docker_help_general
    esac
  fi
}

boot2docker_helplist()
{
  echo "boot2docker:mount_vboxsf"
}

boot2docker_help_general()
{
  echo "General help for the Boot2Docker library

This library provides addtional plugins and functions in order
to allow the local docker implementation to run over boot2docker,
and still have access to the local file system of the project.

Implementations required:
- Share the project file system with the remove VM
- Share the user \${HOME} folder with the VM

- Alter machine mounts so that they point to the VM path,
  instead of the host path.

@NOTE VBoxManage is used for mounts.  It gives us the ability to add and remove mounts, BUT IT DOES NOT GIVE US A WAY TO LIST MOUNTS TO KNOW WHAT WE HAVE ALREADY MOUNTED.
For now we just remount everything and accept VBoxManage errors, but we will likely have to add some kind of static list of paths mounted.

@TODO this library is really in an infant state.  It can do the mapping but it will cause plenty of errors all over the place.
"
}

boot2docker_help_topicnotfound()
{
  echo "Topic not found for Boot2Docker help

We could not find any help for the topic :${1}.  Please refer to the general boot2docker help (boot2docker:general) for a list of topics."
}

boot2docker_help_topic_vboxsf()
{
  echo "boot2docker_mount_vboxsf()


"
}
