#!/bin/sh
#
# Run the default project builds
#

hook_version=2
hook_root="hook_init_020"

# description method
hook_init_020_description()
{
  echo "build default project images"
}

# help method
hook_init_020_help()
{
  echo "
HOOK->FLOW->INIT->020: Build the default project images

[-b|--builds {builds}] : specify an alternate list of builds that should be built

"
}

# execute method
hook_init_020_execute()
{



  hook_init_020_description

}
