#!/bin/sh
#
# Build the project image
#

hook_version=2
hook_root="hook_command_init_post_030"


# description method
hook_command_init_post_030_description()
{
  echo "build default project imags"
}

# help method
hook_command_init_post_030_help()
{
  echo "
HOOK->FLOW->INIT->030: Build the default project image

As this hook is sort of expensive, and is maybe not desired
during some init implementations, it requires a flag to enable
it.

[-n|--buildnow] : build the image.

"
}

# execute method
hook_command_init_post_030_execute()
{

  local project_build="${project_build:-template}"
  local build_execute_now=-1

  local flags=""
  while [ $# -gt 0 ]
  do
    case "$1" in
      -w|--buildnow)
        build_execute_now=0
        ;;
    esac
    shift
  done

  if [ ${build_execute_now} -eq 0 ]; then

    debug --level 6 --topic "HOOK->COMMAND->INIT->POST->030" "Trying to build custom build [build:${project_build}]"

    if docker_image_exists "${project_image}" -eq 0; then

      debug --level 5 --topic "HOOK->COMMAND->INIT->POST->030" "Custom project build already exists [build:${project_build}]"

    else

      debug --level 5 --topic "HOOK->COMMAND->INIT->POST->030" "Building custom project build [build:${project_build}]"
      command_execute "build" --build "${project_build}" --image "${project_image}" --version "${project_imageversion}"

      if [ $? -eq 0 ]; then
        debug --level 5 --topic "HOOK->COMMAND->INIT->POST->030" "Built custom project build [build:${project_build}]"
      else
        debug --level 5 --topic "HOOK->COMMAND->INIT->POST->030" "Could not build custom project build [build:${project_build}]"
      fi
    fi

  else
    debug --level 5 --topic "HOOK->COMMAND->INIT->POST->030" "Not attempting to build the project build, as were not instructed to do so [build:${project_build}]"
  fi
}
