#!/bin/sh
#
# Run the command specific
#

hook_version=2
hook_root="hook_command_post_specific_050"

# description method
hook_command_post_specific_050_description()
{
  echo "HOOK->Command:post:specific: Run any command specific POST hooks"
}

# help method
hook_command_post_specific_050_help()
{
  echo "
HOOK->Command:post:specific: Run any command specific POST hooks
"
}

# execute method
hook_command_post_specific_050_execute()
{

  local command=$1
  shift

  if [ "${command}" == "" ]; then
    # don't run any post hooks if no command is specified
    return
  fi

  # Run all POST hooks for the custom command
  hooks_execute "command/${command}" --state "post" $@
  local success=$?

  if [ $success -eq 0 ]; then
    debug --level 8 --topic "HOOK->COMMAND->POST->050" "Command specific POST hooks run successfully [command:${command}]"
  else
    debug --level 6 --topic "HOOK->COMMAND->POST->050" "Command specific POST hooks failed to run [command:${command}]"
  fi
  return $success
}
