#!/bin/sh
#
# Settings library
#

# Alias list add method
alias_add()
{
  local alias="${1}"

  case "${alias}" in
    @*) # just an marker for aliases from the command line
      alias="${alias:1}"
      ;;
    %*) # load the first part as a lib, then use it as an alias
      alias="${alias:1}"
      library_load "${alias%:*}"
      ;;
    ^*) # laod the first part as a lib, and use the second part as an alias
      alias="${alias:1}"
      library_load "${alias%:*}"
      if [ "${alias}" == "${alias#:*}" ]; then
        alias=""
      else
        alias="${alias#*:}"
      fi
      ;;
  esac

  if [ -n "${alias}" ]; then
    list_add "alias_aliases" "${alias}"
    alias_load "${alias}"
  fi
}
# Alias list retrieve method
aliases_get()
{
  list_get "alias_aliases"
}

# Load an alias
alias_load()
{
  local alias="${1}"
  shift

  local library=""
  local alias_path=""
  for library in `libraries_list`; do
    debug --level 8 --topic "HOOK->SETTINGS->ALIAS->LOAD" "Checking library for aliases [library:${library}][alias:${alias}]"
    _alias_load "${library}" "${alias}" $@
  done
}
function _alias_load()
{
  local library="${1}"
  local alias="${2}"
  shift 2

  local flags=""

  if [ "${alias}" != "${alias%:*}" ]; then
    flags="${flags} --target ${alias#*:}"
    alias="${alias%:*}"
  fi

  alias_path="`library_path "${library}"`/aliases/${alias}"
  if path_is --exec "${alias_path}"; then
    debug --level 6 --topic "HOOK->SETTINGS->ALIAS->_LOAD" "Loading alias library [library:${library}][alias:${alias}][path:${alias_path}][flags:${flags}]"
    path_include "${alias_path}" ${flags} $@
  else
    debug --level 8 --topic "HOOK->SETTINGS->ALIAS->_LOAD" "Library does not implement aliad [library:${library}][alias:${alias}][path:${alias_path}][flags:${flags}]"
  fi
}

###
# Mount related functions
#
#

# Add a mount to the system (of the form host:container)
settings_mount_addmount()
{
  list_add "machine_mountvolumes" $1
}

# get a list of added mounts
settings_mount_getmounts()
{
  local format="list"
  local mounts="`list_get "machine_mountvolumes"`"

  local flags=""
  while [ $# -gt 0 ]
  do
    case "$1" in
      -f|--format)
        format="$2"
        shift
        ;;
      -l|--list)
        format="list"
        ;;
      -m|--mount|--mounts)
        format="mount"
        ;;
      -s|--short)
        format="short"
        ;;
      *)
        break;
    esac
    shift
  done

  # $1 would allow for different formats
  case "${format}" in
    "mount")
      # allow hooks to alter the value
      mounts="`hooks_altervalue "mountvolumes" ${mounts}`"

      local mount=""
      local collect=""
      for mount in ${mounts}; do
        collect="${collect} --volume=`path_expand "${mount}"`"
      done
      echo "${collect}"
      ;;
    "short")
      local mount=""
      for mount in ${mounts}; do
        echo "`path_shorten \"${mount%:*}\"`:${mount#*:}"
      done
      ;;
    *)
      echo "${mounts}"
      ;;
  esac
}

#
# This library doesn't do too much yet,
# other than run a lot of hooks
#

#############################
# include setting overrides #
#############################
#
# all of the usefull settings are made
# in settings hooks
#
settings_init()
{
  # First preprocess aliases
  if [ -n "${alias_aliases}" ]; then
    local alias=""
    local previous_aliases="${alias_aliases}"
    alias_aliases=""
    for alias in ${previous_aliases}; do
      alias_add "${alias}"
    done
  fi

  # Run settings initialization
  debug --level 7 --topic "SETTINGS" "Running settings hooks"

  # execute any existing settings hooks
  debug --level 8 --topic "SETTINGS" "Running settings pre hooks => hooks_execute settings --state pre"
  hooks_execute settings --state "pre" $@
  debug --level 8 --topic "SETTINGS" "Running settings hooks => hooks_execute settings"
  hooks_execute settings
  debug --level 8 --topic "SETTINGS" "Running settings post hooks => hooks_execute settings --state post"
  hooks_execute settings --state "post" $@
  debug --level 8 --topic "SETTINGS" "Finished running settings hooks"

  debug --level 7 --topic "SETTINGS" "Running settings hooks complete"
}
