#!/bin/sh
#
# Settings library
#

# Alias list add method
alias_add()
{
  local alias="${1}"

  case "${alias}" in
    @*) # just an marker for aliases from the command line
      alias="${alias:1}"
      ;;
    %*) # load the first part as a lib, then use it as an alias
      alias="${alias:1}"
      library_load "${alias%:*}"
      ;;
    ^*) # laod the first part as a lib, and use the second part as an alias
      alias="${alias:1}"
      library_load "${alias%:*}"
      if [ "${alias}" == "${alias#:*}" ]; then
        alias=""
      else
        alias="${alias#*:}"
      fi
      ;;
  esac

  if [ -n "${alias}" ]; then
    list_add "alias_aliases" "${alias}"
    alias_load "${alias}"
  fi
}
# Alias list retrieve method
aliases_get()
{
  list_get "alias_aliases"
}

# Load an alias
alias_load()
{
  local alias="${1}"
  shift

  local library=""
  local alias_path=""
  for library in `libraries_list`; do
    debug --level 8 --topic "HOOK->SETTINGS->ALIAS->LOAD" "Checking library for aliases [library:${library}][alias:${alias}]"
    _alias_load "${library}" "${alias}" $@
  done
}
function _alias_load()
{
  local library="${1}"
  local alias="${2}"
  shift 2

  local flags=""

  if [ "${alias}" != "${alias%:*}" ]; then
    flags="${flags} --target ${alias#*:}"
    alias="${alias%:*}"
  fi

  alias_path="`library_path "${library}"`/aliases/${alias}"
  if path_is --exec "${alias_path}"; then
    debug --level 6 --topic "HOOK->SETTINGS->ALIAS->_LOAD" "Loading alias library [library:${library}][alias:${alias}][path:${alias_path}][flags:${flags}]"
    path_include "${alias_path}" ${flags} $@
  else
    debug --level 8 --topic "HOOK->SETTINGS->ALIAS->_LOAD" "Library does not implement aliad [library:${library}][alias:${alias}][path:${alias_path}][flags:${flags}]"
  fi
}
# handler for creating a hook (no messages)
alias_create()
{
  debug --level 9 --topic "SETTINGS->ALIAS->_CREATE" "alias_create"

  # default values
  local name="empty"
  local path="project~"

  while [ $# -gt 0 ]
  do
    case "$1" in
      -l|--library)
        path="${2}~"
        shift
        ;;
      -n|--name)
        name="${2}"
        shift
        ;;
      -p|--path)
        path="$2"
        shift
        ;;
      *)
          break;; # terminate while loop
    esac
    shift
  done

  path="`path_expand "${path}aliases"`"
  path_ensure --dir "${path}"
  path="${path}/${name}"

  if path_is "${path}"; then
    debug --level 4 --topic "SETTINGS->ALIAS->CREATE" "Alias path already exists, so alias was not created [path:${path}]"
  else
    if path_ensure --exec "${path}"; then
      echo "#!/bin/sh
#
# ${name} alias
#

debug --level 8 --topic \"SETTINGS->ALIAS->${name}\" \"${name} alias included : $@\"

# alias feature target
feature_alias_target=\"\"

while [ \$# -gt 0 ]
do
  case \"\$1\" in
    --source-include-path)
      shift
      ;;
    --target)
      feature_alias_target=\"\${2}\"
      shift
      ;;
    *)
      break;
  esac
  shift
done

message \"${name} alias was generated, but never edited.  Make it do something [path:${path}]\"

" > ${path}
      debug --level 6 --topic "SETTINGS->ALIAS->CREATE" "Alias was created [name:${name}][path:${path}]"
    else
      debug --level 4 --topic "SETTINGS->ALIAS->CREATE" "Could not create alias file, so alias was not created [name:${name}][path:${path}]"
    fi
  fi
}


###
# Mount related functions
#
#

# Add a mount to the system (of the form host:container)
settings_mount_addmount()
{
  list_add "machine_mountvolumes" $1
}
# Clear out all mounts
settings_mount_clearmounts()
{
  list_reset "machine_mountvolumes"
}
# get a list of added mounts
settings_mount_getmounts()
{
  local format="list"
  local mounts="`list_get "machine_mountvolumes"`"

  local flags=""
  while [ $# -gt 0 ]
  do
    case "$1" in
      -f|--format)
        format="$2"
        shift
        ;;
      -m|--mount|--mounts)
        format="mount"
        ;;
      -s|--short)
        format="short"
        ;;
      *)
        break;
    esac
    shift
  done

  # $1 would allow for different formats
  case "${format}" in
    "mount")
      # allow hooks to alter the value
      mounts="`hooks_altervalue "mountvolumes" ${mounts}`"

      local mount=""
      local collect=""
      for mount in ${mounts}; do
        collect="${collect} --volume=`path_expand "${mount}"`"
      done
      echo "${collect}"
      ;;
    "short")
      local mount=""
      for mount in ${mounts}; do
        echo "`path_shorten \"${mount%:*}\"`:${mount#*:}"
      done
      ;;
    *)
      echo "${mounts}"
      ;;
  esac
}

####
# Container links management
#

# Add a container link
settings_link_add()
{
  list_add "settings_links" "${1}"
}
# Clear out all links
settings_link_clear()
{
  list_reset "settings_links"
}
# retrieve all container links
settings_link_get()
{
  local format="list"
  local links="`list_get "settings_links"`"

  local flags=""
  while [ $# -gt 0 ]
  do
    case "$1" in
      -f|--format)
        format="$2"
        shift
        ;;
      -l|--link|--links)
        format="link"
        ;;
      -s|--short)
        format="short"
        ;;
      *)
        break;
    esac
    shift
  done

  # $1 would allow for different formats
  case "${format}" in
    "link")
      # allow hooks to alter the value
      links="`hooks_altervalue "machinelinks" ${links}`"

      local link=""
      local collect=""
      for link in ${links}; do
        collect="${collect} --link=${link}"
      done
      echo "${collect}"
      ;;
    "short")
      local link=""
      for link in ${links}; do
        echo "`path_shorten \"${link%:*}\"`:${link#*:}"
      done
      ;;
    *)
      echo "${links}"
      ;;
  esac
}


####
# Container environment variable management
#

# Add a container env
settings_env_set()
{
  list_add "settings_envs" "${1}"
}
# Clear out all links
settings_env_clear()
{
  list_reset "settings_envs"
}
# retrieve all container links
settings_env_get()
{
  local format="list"
  local envs="`list_get "settings_envs"`"

  local flags=""
  while [ $# -gt 0 ]
  do
    case "$1" in
      -f|--format)
        format="$2"
        shift
        ;;
      -e|--export|--exportss)
        format="export"
        ;;
      -s|--short)
        format="short"
        ;;
      *)
        break;
    esac
    shift
  done

  # $1 would allow for different formats
  case "${format}" in
    "export")
      # allow hooks to alter the value
      envs="`hooks_altervalue "machineenvs" ${envs}`"

      local env=""
      local collect=""
      for env in ${envs}; do
        collect="${collect} --env=${env}"
      done
      echo "${collect}"
      ;;
    "short")
      local env=""
      for env in ${envs}; do
        echo "${env}"
      done
      ;;
    *)
      echo "${envs}"
      ;;
  esac
}

#
# This library doesn't do too much yet,
# other than run a lot of hooks
#

#############################
# include setting overrides #
#############################
#
# all of the usefull settings are made
# in settings hooks
#
settings_init()
{
  # Run settings initialization
  debug --level 7 --topic "SETTINGS" "Running settings hooks"

  # execute any existing settings hooks
  debug --level 8 --topic "SETTINGS" "Running settings pre hooks => hooks_execute settings --state pre"
  hooks_execute settings --state "pre" $@
  debug --level 8 --topic "SETTINGS" "Running settings hooks => hooks_execute settings"
  hooks_execute settings
  debug --level 8 --topic "SETTINGS" "Running settings post hooks => hooks_execute settings --state post"
  hooks_execute settings --state "post" $@
  debug --level 8 --topic "SETTINGS" "Finished running settings hooks"

  debug --level 7 --topic "SETTINGS" "Running settings hooks complete"
}

# Execute handler
settings_execute()
{

  if [ -z "${1}" ]; then
    # @NOTE I can't decide what the default behaviour should be
    # help_execute "settings:general"
    help_execute "settings:settings"
  else
    case "${1}" in
      alias)
        shift
        case "${1}" in
          create)
            shift
            message "Creating alias $@"
            alias_create $@
            ;;
          *)
            help_execute "settings:aliases"
        esac
        ;;
      settings|show|all)
        shift
        help_execute "settings:settings"
        ;;
      *)
        help_execute "settings:${1}"
    esac
  fi
}
