#!/bin/sh
#
# Settings library
#

###
# Mount related functions
#
#

# Add a mount to the system (of the form host:container)
settings_mount_addmount()
{
  list_add "machine_mountvolumes" $1
}
# get a list of added mounts
settings_mount_getmounts()
{
  # $1 would allow for different formats
  case $1 in
    *)
      local mounts=""
      local mount=""
      for mount in `list_get "machine_mountvolumes"`; do
        mounts="$mounts --volume=${mount}"
      done
      echo "${mounts}"
      ;;
  esac
}

#
# This library doesn't do too much yet,
# other than run a lot of hooks
#

#############################
# include setting overrides #
#############################
#
# all of the usefull settings are made
# in settings hooks
#

debug --level 7 --topic "SETTINGS" "Running settings hooks"

# execute any existing settings hooks
debug --level 8 --topic "SETTINGS" "Running settings pre hooks => hooks_execute settings --state pre"
hooks_execute settings --state "pre" $@
debug --level 8 --topic "SETTINGS" "Running settings hooks => hooks_execute settings"
hooks_execute settings
debug --level 8 --topic "SETTINGS" "Running settings post hooks => hooks_execute settings --state post"
hooks_execute settings --state "post" $@
debug --level 8 --topic "SETTINGS" "Finished running settings hooks"

debug --level 7 --topic "SETTINGS" "Running settings hooks complete"
