#!/bin/sh
#
#
#

hook_version=2
hook_root="hook_docker_run_post_200"

# description hook
hook_docker_run_post_200_descrtiption()
{
  echo "register any new containers in the system"
}

# help method
hook_docker_run_post_200_help()
{
  echo "
HOOK->DOCKER->RUN->POST->200 Register any new containers in the system

Any new container has a file created here: ${docker_container_registerpath}

"
}

# execute method
hook_docker_run_post_200_execute()
{

  local flags=""
  while [ $# -gt 0 ]
  do
    case "$1" in
      -c|--container)
        local container=$2
        shift
        ;;
      -d|--id)
        local containerID=$2
        shift
        ;;
      -e|--execute)
        local command="${2}"
        shift
        ;;
      -h|--hostname)
        flags="${flags} --hostname=\"$2\""
        shift
        ;;
      -i|--image)
        local image="${2}"
        shift
        ;;
      -n|--ip)
        local ip="${2}"
        shift
        ;;
      -v|--version)
        local version="${2}"
        shift
        ;;
      -P|--allports)
        flags="${flags} --publish-all=true"
        ;;
      --startargs)
        shift
        break
        ;;
      *)
        break;; # terminate while loop
    esac
    shift
  done

  if [ "${docker_container_registerpath}" != "${empty_path}" ]; then

    if ! path_ensure --dir "${docker_container_registerpath}"; then
      debug --level 5 --topic "HOOK->DOCKER->RUN->POST->200" "Could not create container registration file, as the path cannot be used : ${docker_container_registerpath}"
      return 1
    fi

    if [ -n "${container}" ]; then

      local path="${docker_container_registerpath}/$container"

      if path_is "${path}"; then
        debug --level 5 --topic "HOOK->DOCKER->RUN->POST->200" "Overwriting existing container registration file : ${path}"
      else
        debug --level 5 --topic "HOOK->DOCKER->RUN->POST->200" "Creating new container registration file : ${path}"
      fi

      echo "id:${containerID}
container:${container}
image:${image}
version:${version}
ip:${ip}
args:$@"  > ${path}

    else
      debug --level 5 --topic "HOOK->DOCKER->RUN->POST->200" "Could not create container registration file, as no container name was passed [container:${container}"
    fi

  else
    debug --level 5 --topic "HOOK->DOCKER->RUN->POST->200" "Could not create container registration file, as no container registration path was found [container:${container}"
  fi
}
