#!/bin/sh
#
# Help hander
#

# execute method
platform_help()
{
  platform_help_generalhelp
}
# list method
platform_helplist()
{
  local helplist='there is no help list for this library'
}

# execute method
platform_help_generalhelp()
{
  echo "Platform.sh library

The Platform library is a toolset/API library that provides an interactive
platform cli container for that can be used for any platform interactions
on a project.
"
  help_scope_add "platform"
  help_scope_list
}