#!/bin/sh
#
# Help hander
#

# execute method
platform_help()
{
  if [ -n "${1}" ]; then

    case "${1}" in

      *)
        echo "Unknown platform help topic : $1

You asked for help on an unknow docker topic

"
      ;;
    esac

  else

    echo "Help for the Platform library

The Platform library is a toolset/API library that provides an interactive
platform cli container for that can be used for any platform interactions
on a project.
"

    help_scope_add "platform"
    help_scope_list

  fi
}
# list method
platform_helplist()
{
  echo ""
}
