#!/bin/sh
#
# HOOK->SETTINGS->INIT->POST->900 Output debug settings if asked to
#

hook_version=2
hook_root="hook_settings_init_post_900"

# description method
hook_settings_init_post_900_description()
{
  echo "Output debug settings if asked to"
}

# help method
hook_settings_init_post_900_help()
{
  echo "HOOK->SETTINGS->INIT->POST->900 Output debug settings if asked to

This is a debugging tool that allows you to output the settings that are
configured after tool initialization, to validate what values are being
used.

The output only occurs if the debug level is 5 or greater, or if the
\${settings_debug_output} variable is set to 0 (true).  You can set that
variable in any library.
  - set this in your user folder ~/.boch/settings to enable output on all projects
  - set this in your project folder /.boch/settings to enable output on this projects
  - use the @settings:output alias to enforce this values

  - currently, settings any debug level 5 and greater will enable this

@NOTE some settings can change after this output.
"
}

# execute method
hook_settings_init_post_900_execute()
{
  if [ ${settings_debug_output:-1} -eq 0 ] || [ `debug_get_level` -gt 4 ]; then
    help_execute "settings:settings"    
    echo " " # put a line after the settings
  fi
}
