#!/bin/sh
#
# remote Feature settings
#

# Just in case this is side-loaded
library_load "feature"

# Name of this feature
feature_name="aspired_remote"
# Path to this feature
feature_path="/Users/mik/env/aspired/.boch/features/aspired_remote"

#project_image="csb_squeeze_php53"
#project_container="test"
settings_env_set "HOME:/root"