#!/bin/sh
#
# FLOW->STATUS : Tell status that this library is enabled
#

hook_version=2
hook_root="hook_mylibrary_flow_status_500"

# Description method
#
# This description is used in help lists, when lists of hooks
# that affect a scope are shown.
hook_mylibrary_flow_status_500_description()
{
  echo "Output during status flow that the mylibrary example library is enabled"
}

# help method
#
# Proovide full help text for the hook, including which arguments
# it may depend on
hook_mylibrary_flow_status_500_help()
{
  echo "hook->flow->status->500 : Tell status that this library is enabled

  This hook outputs that this library is active, during execution of the
  status flow.
"
  help_scope_add "flow:status"
}

# execute method
hook_mylibrary_flow_status_500_execute()
{
  echo "== MY LIBRARY ==
--Example library is Enabled!!!"
}
