#!/bin/sh
#
# HOOK : command:pre : 020 load command
#

hook_version="2"
hook_root="hook_command_pre_020"

# description method
hook_command_pre_020_description()
{
  echo "hook->command:pre 020 : Load the command script file"
}

# help function
hook_command_pre_020_help()
{
  echo "
hook->command:pre 020 : Load the command script file

"
}

# execute function
hook_command_pre_020_execute()
{
  # Command is the first argument
  COMMAND=$1

  # We have a command file, so we hand the execution off to
  # that script to run inline (not as a function)
  _include_command ${COMMAND}
  local success=$?

  if [ $success -gt 0 ]; then

    # no command was found
    _hook_command_pre_020_notfound
    debug --level 1 --topic "HOOK->COMMAND->PRE->020" "failed to load.  Unkown command [command:${COMMAND}]"

    return 1
  fi
}

_hook_command_pre_020_notfound()
{
echo "
Command not found: Unknown command \"${COMMAND}' - try using 'control help' for instructions.
"
}
