#!/bin/sh
#
# Run the command specific
#

hook_version=2
hook_root="hook_command_pre_specific_060"

# description method
hook_command_pre_specific_060_description()
{
  echo "HOOK->Command:pre:specific: Run any command specific PRE hooks"
}

# help method
hook_command_pre_specific_060_help()
{
  echo "
HOOK->Command:pre:specific: Run any command specific PRE hooks

"
}

# execute method
hook_command_pre_specific_060_execute()
{

  local COMMAND=$1
  shift

  # Run all PRE hooks for the custom command
  hooks_execute
  local success=$?
  if [ $success -gt 0 ]; then
    debug --level 8 --topic "HOOK:COMMAND:${COMMAND}:PRE" "Command specific PRE hooks run successfully"
  else
    debug --level 6 --topic "HOOK:COMMAND:${COMMAND}:PRE" "Command specific PRE hooks failed to run"
  fi
  return $success
}
