#!/bin/sh
#
# Flow Library
#

# list all flows in the system
flows_getflows()
{
  local flow=""
  local flow_paths="`libraries_contents --dir --subpath \"hooks/flow\"`"
  echo "`for flow in ${flow_paths}; do
    echo "${flow##*/}"
  done | sort -u`"
}

# determing if a flow exists
flow_exists()
{
  local flow="$1"

  local flow_path=""
  local state=""
  for state in help pre execute post; do
    for flow_path in `hooks_list --state "${state}" "flow/${flow}"`; do
      return 0
    done
  done

  return 1
}
