#!/bin/sh
#
# HOOK: command : 050 Command execute
#

hook_version="2"
hook_root="hook_command_050"

# description method
hook_command_050_description()
{
  echo "hook->command 050 : execute the command hook_execute method"
}

# Help function
hook_command_050_help()
{
echo "
hook->command 050 : execute the command hook_execute method

Run the command include hook_execute method, which is the target function
that impements the functionality.
If the function fails, then run the fail hooks.
"
}

# execute function
hook_command_050_execute()
{
  # Command is the first argument
  COMMAND=$1
  shift

  command_execute $COMMAND $@
  success=$?
  if [ $success == 0 ]; then
    echo "$result"
    debug --level 6 --topic "HOOK:COMMAND:050" "${COMMAND} succeeded."

  else
    debug --level 2 --topic "HOOK:COMMAND:050" "Command execution failed for command ${COMMAND}."

    # execute any existing post hooks
    debug --level 7 --topic "HOOK:COMMAND:050" "Running global:fail hooks => hooks_execute global --state \"fail\" --command \"${COMMAND}\""
    hooks_execute command --state "fail" --command "${COMMAND} $@"
  fi
  exit $sucess

}
