#!/bin/sh
#
# INIT:HOOK: Create the custom project folder
#

hook_version=2
hook_root="hook_init_050"

# descriptoin method
hook_init_050_description()
{
  echo "Create the custom project folder, if missing."
}

# help method
hook_init_050_help()
{
  echo "
hook->init->050 : Create the custom conf folder for the project

This hook will create a new root level folder for your project
in which all of your settings, and custom project code can go.

The folder will always be /boch
"

}

# execute method
hook_init_050_execute()
{
  # what is the root path to the project folder
  local path="${path_projectconf:-${path_project}/boch}"

  if ! path_is --dir "${path_projectconf}"; then
    # path to the executable library handler, in the library folder
    local path_projectconf_executable="`library_handler "project:${path}"`"

    debug --level 5 --topic "HOOK->COMMAND->INIT->050" "Making sure that we have a project conf library folder and handler [path:${path_projectconf%/*}][name:${path_projectconf##*/}][handler:${path_projectconf_executable}]"
    # make sure that we have a custom library in the data path
    library_create --complex --path "${path_projectconf%/*}" "${path_projectconf##*/}"
  fi
}
