#!/bin/sh
#
# INIT:HOOK: Possible include additional libraries during init
#

hook_version=2
hook_root="hook_flow_init_pre_900"

# descriptoin method
hook_flow_init_pre_900_description()
{
  echo "Include the additional libraries during init, if told to do so"
}

# help method
hook_flow_init_pre_900_help()
{
  echo "hook->init->pre->090 : Include additional libraries, if told to do so

This hook will include additional libraries during init, where they can
then implement hooks, add settings, enable specific builds, and
add other features.

  [-l|--libraries {additional libraries} : list which additional libraries
      should be loaded during init.

  [--boot2docker] : include the boot2docker as a dependency; This library
      will add settings and handlers for running docker through boot2docker.

  [--www-builds] {www-build-library} : include the www-builds library, and
    indicate that one of the builds will be needed.

@NOTE that this option does not make these libraries loaded during
  subsequent calls to the system.  If a library wants to self-load,
  it should add a library_load call to a settings/default hook, to
  have it added to the default settings file. The boot2docker is a
  good example to follow.
"
}

# execute method
hook_flow_init_pre_900_execute()
{
  additional_libraries=""

  local flags=""
  while [ $# -gt 0 ]
  do
    case "$1" in
      -l|--libraries)
        # load any libraries, consider that the value may be comma delimited
        additional_libraries="${additional_libraries} ${2/,/ }"
        shift
        ;;

      --boot2docker)
        # straight target for the boot2docker library
        additional_libraries="${additional_libraries} boot2docker"
        ;;
      --www-build|--www-builds)
        additional_libraries="${additional_libraries} www-builds"
        # treat the argument as an alias target, that www-builds will handler
        alias_add "www-builds:${2}"
        shift
        ;;
    esac
    shift
  done

  local library=""
  for library in ${additional_libraries}; do
    if ! library_loaded "${library}"; then
      debug --level 5 --topic "HOOK->FLOW->INIT->PRE->900 Loading the ${library} library as directed"
      library_load "${library}"

      if [ $? -gt 0 ]; then
        debug --level 5 --topic "HOOK->FLOW->INIT->PRE->900 Error occured loading the ${library} library as directed"
        return 1
      fi
    fi
  done
  return 0
}
