#!/bin/sh
#
# COMMAND: Mount a host folder in the Boot2Docker VM
#

# Description method
b2dmount_description()
{
  echo "Mount a host folder in the Boot2Docker VM"
}

# Help Method
bd2mount_help()
{
  echo "Help for the b2dmount command

This command will let you mount a host path onto the remove VM

@NOTE there is currently no method to determine if a path has already been mounted
  which means that we can expect errors in many cases
"

  help_scope_add "boot2docker:mount_vboxsf"

  help_scope_list
}

# Execute Method
b2dmount_execute()
{

echo "MOUNT B2D PATH"

}
