#!/bin/sh
#
# Help hander
#


# help method
wwwcnpmjn_help()
{
  wwwcnpmjn_help_generalhelp
}

# method to list all flow topics in scope
# @NOTE there are no help topics for this library
wwwcnpmjn_helplist()
{
  echo ""
}

# generic help message for the command help system
# @TODO put some usefull material here
wwwcnpmjn_help_generalhelp()
{
  echo "Help for the WWW-CNPM(JN) WWW SERVER Library

This library adds a number of preconfigured builds to the system, to
provide it with a decent CENTOS 7 based web server.
Included are some builds, a template build, and some related settings

The library includes some CENTOS builds, but does not required that you
build them, it rather includes a template build, that is based on a
docker.io version of the builds.  The other builds are included for you
to re-use and modify as needed.

You should include this library if you are using these builds, as the
library will include settings that work well for the builds.
Most of the settings are included as \"default settings\" provided, as
opposed to being included at every execution (this way you can override
whatever you need.)

You can include the library simply by adding the following to your project
script or settings file: library_load \"wwwcnpmjn\"

Better is to include the --wwwserver flag when using the init flow:
$/> ./flow init --www-cnpm-jn

"
}
