#!/bin/sh
#
# HOOK: INIT:help : describe the flow command
#

hook_root="hook_core_init_help_010"
hook_version="2"

# description hook method
hook_core_init_help_010_description()
{
  echo "Flow:help: Generic instructions on how to use help"
}

hook_core_init_help_010_help()
{
  echo "
FLOW: HELP

GENERAL INSTRUCTION ON HOW TO USE FLOW

"
}

# Execute method - as this is a help hook, it just outputs the help
hook_core_init_help_010_execute()
{
  hook_core_init_help_010_help
}
