#!/bin/sh
#
# HOOK: INIT:help : describe the flow command
#

hook_root="hook_core_init_help_010"
hook_version="2"

# description hook method
hook_core_init_help_010_description()
{
  echo "Generic instructions on how to use help with the ./flow tool"
}

hook_core_init_help_010_help()
{
  echo "
FLOW: HELP

GENERAL INSTRUCTION ON HOW TO USE FLOW

- explain the idea behind flow
- explain that flow is entirely hook based
  - explain why the system can't respond to an unknown flow
- show how to get a list of hooks used in a flow

- show examples of getting help for a flow
- show examples of getting help for a flow hook

"
}

# Execute method - as this is a help hook, it just outputs the help
hook_core_init_help_010_execute()
{
  hook_core_init_help_010_help
}
