#!/bin/sh
#
# Try to make sure that there is a user library folder
#

hook_version=2
hook_root="hook_command_init_400"


# description method
hook_command_init_400_description()
{
  echo "Try to make sure that there is a user library folder"
}

# help method
hook_command_init_400_help()
{
  echo "HOOK->FLOW->INSTALL->400: Try to make sure that there is a user library folder

This hook will try to ensure that there is a user oriented library folder, to share across
all user projects.  This will give access to shared functionality, but it also provides system
level support for libraries like boot2docker, which store settings across projects
"
}

# execute method
hook_command_init_400_execute()
{
  if [ -z "${path_userconf}" ] || [ "${path_userconf}" == "${empty_path}" ]; then
    path_userconf="${path_userhome}/${path_userconf_subpath}"
    debug --level 5 --topic "HOOK->COMMAND->INSTALL->400" "No user project path was found, so a new one will be created [path:${path_userconf}]"

    message "Creating boch user library at ${path_userconf}"
    library_create --complex --include-settings --path "${path_userconf%/*}" "${path_userconf##*/}"
    if [ $? -eq 0 ]; then
      debug --level 5 --topic "HOOK->COMMAND->INSTALL->400" "Created a new user library [path:${path_userconf}]"
    else
      debug --level 4 --topic "HOOK->COMMAND->INSTALL->400" "Failed to create a new user library [path:${path_userconf}]"
      return 1
    fi
  fi
}
