#!/bin/bash
#
# HOOK->FEATURE->UPDATE->500 Copy source www into the feature
#

hook_version=2
hook_root="hook_feature_sync_500"

# description method
hook_feature_sync_500_desription()
{
  echo "Copy source www into the feature"
}

# help method
hook_feature_sync_500_help()
{
  echo "HOOK->FEATURE->CREATE->500 Copy source www into the feature

Put a copy of the source into the webroot.

"
}

# Execute method
hook_feature_sync_500_execute()
{
  if [ -n "${feature}" ]; then
    library_load 'command'
    command_load 'sync'
    if [ $? -gt 0 ]; then
      debug --level 5 --topic 'FEATURE->SYNC' 'Cannot load the sync command, which is needed to sync the feature'
      return 1
    fi
    local each_feature_path=''
    for each_feature_path in `feature_path_get`; do
      if path_in "${feature_path}" "${each_feature_path%:*}"; then

        # we need to sync this path
        debug --level 5 --topic 'FEATURE->SYNC' "syncing feature path [path:${each_feature_path#*:}][feature_path:${each_feature_path%:*}]"
        message "Syncing feature file path : ${each_feature_path#*:} -> ${each_feature_path%:*}"
        command_execute 'sync' --action 'sync' "${each_feature_path#*:}" "${each_feature_path%:*}"

      fi
    done
  else
    message "Could not sync the feature from the system, as it was not found: ${feature_path}"
    debug --level 5 --topic "FEATURE->SYNC" "Could not sync feature, not found [path:${feature_path%:*}]"
  fi

  return 0
}
