#!/bin/sh
#
# Run the default project builds
#

hook_version=2
hook_root="hook_init_020"

# description method
hook_init_020_description()
{
  echo "flow->init hook 020: build default project images"
}

# help method
hook_init_020_help()
{
  echo "
Flow->init hook 020: Build the default project images

[-b|--builds {builds}] : specify an alternate list of builds that should be built

"
}

# execute method
hook_init_020_execute()
{

  echo "default builds"

}