#!/bin/sh
#
# HOOK : command:pre : 020 load command
#

hook_version="2"
hook_root="hook_command_pre_020"

# description method
hook_command_pre_020_description()
{
  echo "hook->command:pre 020 : Load the command script file"
}

# help function
hook_command_pre_020_help()
{
  echo "
hook->command:pre 020 : Load the command script file

"
}

# execute function
hook_command_pre_020_execute()
{
  # Command is the first argument
  COMMAND=$1


  debug --level 4 --topic "HOOK->COMMAND->PRE->020" "Loading command [command:${COMMAND}]"

  # We have a command file, so we hand the execution off to
  # that script to run inline (not as a function)
  command_include ${COMMAND}
  local success=$?

  if [ $success -gt 0 ]; then
    debug --level 4 --topic "HOOK->COMMAND->PRE->020" "Command load failed [command:${COMMAND}]"

    # execute any existing post hooks
    debug --level 7 --topic "HOOK->COMMAND->050" "Running global:fail hooks => hooks_execute command --state \"fail\" \"${COMMAND}\" $@"
    hooks_execute "command" --state "fail" "${COMMAND}" $@
    return 1
  fi
}
