#!/bin/sh
#
# HOOK->FLOW->STATUS->HELP->500 General help for the "status" flow
#

hook_version=2
hook_root="hook_flow_status_help_500"

# description method
hook_flow_status_help_500_description()
{
  echo "General help text for the status flow"
}

# help method
hook_flow_status_help_500_help()
{
  echo "
HOOK->FLOW->STATUS->HELP->500 General help for the "status" flow

This hook gives general help text for the status flow

"
}

# execute method
hook_flow_status_help_500_execute()
{
  echo "
STATUS FLOW

This flow gives general status for the current project. It checks
various status topics, usually one per hook, as directed by the passed
topic list, but falling back to a default topic list.
The topic list can be manually added to the command line, but you
can also define topic lists using aliases, to get presets that you
like (settings:alias).  You can define those aliases per user, or
per project, as makes sense.

Usage:

  $/> ./flow status <options> <topics>

Options: (all used in hooks)
  [-b|--build {build}] : Consider the passed build as active
  [-c|--container {container}] : Consider the passed container as active
  [-i|--image {image}] : Consider the passed image as active

Topics:

  all : All the things

  help : some help information on the flow
  settings : Output settings and variables
  image : Output image information
  build : Output build information

  cont.all : all container output
  cont.active : active container
  cont.image : containers related to the active image
  cont.registered : All containers registered in the project

@NOTE the default set is : \"${status_flow_topics_default}\"
@NOTE if you have a favorite list of items, you can set the
   \"flow_status_topics\" variable either in project/user  settings,
   or using aliases.
   This flow will check the variable for values, and add passed
   topics to the list.
"
}
