#!/bin/sh
#
# HOOK->FLOW->STATUS->320 Project containers
#

hook_version=2
hook_root="hook_flow_status_320"

# description method
hook_flow_status_320_description()
{
  echo "Analyze containers used in the project"
}

# help method
hook_flow_status_320_help()
{
 echo "HOOK->FLOW->STATUS->320 Project image containers

Attempt to list all of the containers related to a project image.
The hook will, if directed by status topics, output a list of containers
that use the image.
"
}

# execute method
hook_flow_status_320_execute()
{
  case " ${flow_status_topics} " in
    *" all "*|*" cont.all "*|*" cont.image "*|*" container.all "*|*" container.image "*)

      echo "
IMAGE CONTAINERS
================"

      if [ "${image}" != "" ] && docker_image_exists "${image}"; then
        echo "Containers related to the project image:
-->project_image:${image}
CONTAINER ID        IMAGE               COMMAND             CREATED             STATUS              PORTS               NAMES"
        docker_inspect_container_list --image "${image}"
      fi

      ;;
  esac
}
