#!/bin/sh
#
# WWW Server library
#
# This library does little more than provide some optional prepackaged build
# libraries, one of which could be used to include some of our pre-built server
# builds, and related settings.
#
# This library came about when we separated the www-servers that we built from
# the toolset, and then realized that we had two good different builds. So
# we included them as libraries of their own.  As they are not likely to be the
# last builds, I thought to create this library to contain any number of future
# builds.
#

# Add a library build to the list
www_builds_list_add()
{
  list_add "wwwbuilds_buildlist" "${1}"
}
# get the library build list
www_builds_list_get()
{
  list_get "wwwbuilds_buildlist"
}

# initialize the docker library
www_builds_path=""
www_builds_init()
{
  # default flags
  local flags=""
  while [ $# -gt 0 ]
  do
    case "$1" in
       --path)
        www_builds_path="${2}"
        shift
        ;;
      *)
        break;; # terminate while loop
    esac
    shift
  done

  local path=""
  for path in `path_contents --library "${www_builds_path}/libraries"`; do
    www_builds_list_add "${path##*/}:`path_shorten "${path}"`"
  done
}
