#!/bin/sh
#
# WWW Server library
#
# This library does little more than provide some optional prepackaged build
# libraries, one of which could be used to include some of our pre-built server
# builds, and related settings.
#
# This library came about when we separated the www-servers that we built from
# the toolset, and then realized that we had two good different builds. So
# we included them as libraries of their own.  As they are not likely to be the
# last builds, I thought to create this library to contain any number of future
# builds.
#

# get the library build list
www_builds_list_get()
{
  local lib="`libraries_list_get "www-builds"`"
  local builds_path="`library_path "${lib}"`/libraries"
  for path in `path_contents --library "${builds_path}"`; do
    echo "${path##*/}:`path_shorten "${path}"`"
  done
}
