#!/bin/sh
#
# Help handler for the builds library
#

# help topic handler
builds_help()
{
  if [ -z "${1}" ]; then
    builds_help_generalhelp

    help_scope_add "builds:general"
    help_scope_list
  else
    local buildlib=""
    for buildlib in `builds_list_get`; do
      if [ "${1}" == "${buildlib%:*}" ]; then
        builds_help_topichelp "${buildlib}"
      fi
    done
  fi

}
# help topic provider
builds_helplist()
{
  if [ -z "${1}" ]; then
    local buildlib=""
    echo "The following libraries are www-build libraries (they have their own help topics):"
    for buildlib in `builds_list_get`; do
      echo "--> ${buildlib%:*} (builds:${buildlib%:*}) `library_path "${buildlib}"`"
    done
  else
    echo ""
  fi
}

# General help text
builds_help_generalhelp()
{
  echo "General help for the builds library

This library is a collection of other libraries that are meant to give
access to www server builds.  The www libs are various docker builds
that have been collected as a part of the project.

Note that this library, and the related build libraries are not really
needed after a project has been initialized.  Each build library should
give a project enough settings and pieces to run without the library
after the init flow has been executed.
"
}

# Topic help
# @NOTE we hand of any topic/library help to the handler for that library
builds_help_topichelp()
{
  local library="${1}"
  library_load "${library%:*}"
  help_execute "${library%:*}"
}
