#!/bin/sh
#
# INIT:HOOK: Describe you hook
#
# @NOTE this hook will only execute if IT IS EXECUTABLE
# @NOTE that the file name used has the number prefix to sort
#     across all hooks that are in scope, across all folders
#

# Hook version is always 2, it tells the hook handler that
# you will have the description, help and execute methods
hook_version=2
# Hook root is the base of all function names in this hook
hook_root="hook_example_500"

# Descriptionn method
#
# This description is used in help lists, when lists of hooks
# that affect a scope are shown.
hook_example_500_description()
{
  echo "Provide a 1-line description of your hook"
}

# help method
#
# Proovide full help text for the hook, including which arguments
# it may depend on
hook_example_500_help()
{
  echo "hook->example->500 : Example hook help header

Describe the hook

  [-a|--argument {additional parameter} : describe what arguments
      the hook may act on

@NOTE add some useful notes

@TODO indicate what work still needs to be done
"
}

# execute method
hook_example_500_execute()
{
  echo "Hook example is acting now!"
}
