#!/bin/sh
#
# An example /bin handler for making the boch toolset
# globally available, instead of putting it into each
# project home folder.
#
# To use, copy this into any bin folder:
# ~/bin /usr/local/bin, /usr/bin
# And cuztomize the path_manage variable to point to
# your global copy of the toolset.
#
# Path to the boch toolset folder
path_manage="/path/to/the/boch/toolset
# Hand off to the toolset
source "${path_manage}/boch" $@
