#!/bin/sh
#
# Configurable settings for the project
#

hook_version=2
hook_root="hook_flow_init_900"

# description method
hook_flow_init_900_description()
{
  echo "Load the custom project/data folder as a library"
}

# help method
hook_flow_init_900_help()
{
  echo "hook->settings->900 Include the project as a library

This hooks attempts to load the custom data/project folder as a library,
to include any settings from the folder. This needs to be done so that
any post hooks have access to the project settings, if we have only just
now created the project folder.

@NOTE so far, the only case in which this hook does anything is if you
  are running the init flow, and it has just created the project folder.
@NOTE there is a chance that elements created in an existing project
  folder are not loaded, but most libraries should be late checking
  libraries for their requirements.
"
}

# execute method
hook_flow_init_900_execute()
{
  if ! library_loaded "project"; then
    # library_load checks to see if a library is already loaded, so no worries about
    # reloading an existing project folder.
    message "Loading new project core library"
    library_load --path "${path_projectconf}" "project"
    if [ $? -gt 0 ]; then
      debug --level 3 --topic "HOOK->SETTINGS->FLOW->INIT->900" "No custom data/project folder exists [path:${path_projectconf}]"
    else
      debug --level 5 --topic "HOOK->SETTINGS->FLOW->INIT->900" "Loaded Data/Project folder as a library [path:${path_projectconf}]"
    fi
  fi

  # don't fail, even if we had problems.  This shouldn't break anything
  return 0
}
