#!/bin/sh
#
# HOOK->FLOW->STATUS->200 Status flow help
#

hook_version=2
hook_root="hook_settings_flow_status_200"

# description method
hook_settings_flow_status_200_description()
{
  echo "Status flow help"
}

# help method
hook_settings_flow_status_200_help()
{
 echo "HOOK->FLOW->STATUS->200 Status flow help
"
}

# execute method
hook_settings_flow_status_200_execute()
{
  case " ${flow_status_topics} " in
    *" all "*|*" settings "*)
      help_execute "settings:settings"
      ;;
  esac
}
