#!/bin/sh
#
# HOOK->FEATURE->UPDATE->HELP->500 General help for the feature:update
#

hook_version=2
hook_root="hook_feature_update_help_500"

# description method
hook_feature_update_help_500_description()
{
  echo "General help text for the feature update action"
}

# help method
hook_feature_update_help_500_help()
{
  echo "
HOOK->FEATURE->UPDATE->HELP->500 General help for feature:update

The purpose of this flow is make the project source match the
feature source.

Combined with feature:sync, this should allow you to maintain a copy
of certain project source files and folder independently in the feautre
to keep an isolated file system for mapping into the feature

FEATURE UPDATE

Update project source from the feature

Paths considered eligible for sync/update/empty should be added using
the feature_path_add function:
  feature_path_add \"\${feature_name}~source/www/:root~source/www/\"

Usage:

  $/> ./boch feature update <options> <feature_name>

Options: (all used in hooks)

"
  help_scope_add "feature:general"
  help_scope_list
}

# execute method
hook_feature_update_help_500_execute()
{
  hook_feature_update_help_500_help
}
