#!/bin/sh
#
# Feature alias, to load aliased www-builds libraries
#"

debug --level 8 --topic "WWWBUILDS->ALIAS" "WWW-Build alias included : $@"

# alias feature target
wwwbuild_alias_target=""

while [ $# -gt 0 ]
do
  case "$1" in
    --source-include-path)
      shift
      ;;
    --target)
      wwwbuild_alias_target="${2}"
      shift
      ;;
    *)
      break;
  esac
  shift
done

if [ -n "${wwwbuild_alias_target}" ]; then
  library_load "${wwwbuild_alias_target}"
  if [ $? -eq 0 ]; then
    debug --level 5 --topic "WWWBUILDS->ALIAS" "www-builds library loaded via alias [library:${wwwbuild_alias_target}]"
  else
    debug --level 4 --topic "WWWBUILDS->ALIAS" "Unable to load a www-builds library via alias [library:${wwwbuild_alias_target}]"
  fi
fi
