#!/bin/sh
#
# Add platform configurations to the default settings
#

hook_version=2
hook_root="hook_platform_default_700"

hook_platform_default_700_description()
{
  echo "Add platform configurations to the default settings"
}

hook_platform_default_700_help()
{
  echo "HOOK->SETTINGS->DEFAULT->010 Add platform sh info to the default settings file"
}

hook_platform_default_700_execute()
{
  echo "####
# Platform Settings
#
# Different settings that can be made to set up the platform environment
# that will apply whenever the platform library is loaded.
#

# Some settings default values
#
# @NOTE you probably don't need to change these, as they point to standard
#     locations for configurations that will be included into the platform
#     containers.
#
#platform_settings_user_path=\"${platform_settings_user_path}\"
#platform_settings_project_path=\"${platform_settings_project_path}\"

# Configure the platform working directory, from which platform commands will be run
#platform_settings_workdir=\"/app/source\"

"
}
