#!/bin/sh
#
# Create and get shell access to a temporary container based on the
# images that is generated by this Dockerfile when it is run
# Really this is used for testing
#
docker run --rm -t -i -h wklv-www-cnpm-dev -u developer -e HOME=/home/developer -P wklv-www-cnpm /bin/zsh
