#!/bin/sh
#
# INIT:HOOK: Convert flow arguments into global variables
#

hook_version=2
hook_root="hook_flow_init_030"

# descriptoin method
hook_flow_init_030_description()
{
  echo "Interpret the passed arguments as global variables"
}

# help method
hook_flow_init_030_help()
{
  echo "hook->init->030 : Create the custom folder for the project

This hook will attempt to interpret the flow arguments into
global variables, which will reduce the dependence on args
for following hooks.
Following hooks won't need to interpret flow arguments as
much, and can depend on global settings.

  [-l|--libraries] \"{additional libraries}\"] : load additional libraries during init to
     allow them to add settings and implement hooks.

  [-b|--bin-location {bin/path}] : select an alternative location to use for the \"bin\" link
      which is installed to make the toolset globally available.  The default is ~/bin
"
  help_scope_add "hook:flow/init"
}

# execute method
hook_flow_init_030_execute()
{

  # bin path to install the symlink
  path_bin="${path_bin:-${path_userhome}/bin}"

  local flags=""
  while [ $# -gt 0 ]
  do
    case "$1" in
      -b|--bin-location)
        path_bin="${2}"
        shift
        ;;
      -l|--libraries)
        additional_libraries="${additional_libraries} ${2}"
        shift
        ;;
      *)
        break;
    esac
    shift
  done

}
