#!/bin/sh
#
# hook:help Main help handler
#

hook_version="2"
hook_root="hook_help_docker_050"

show_global_hooks="no"

# description method
hook_help_docker_050_description()
{
  echo "Main help handler for the command tool"
}

# help method
hook_help_docker_050_help()
{
  echo "
hook->help: Main help handler

This hook is the primary command help executor.  It will
write generic help to the screen, or it will load and
write command specific, and command and hook specific
help to the screen.

To get generic help try running without a command.
$/> ./command --help

"
}
# execute method
hook_help_docker_050_execute()
{
  if [ -n "${1}" ]; then

    case "${1}" in
      "docker_build")
        echo "
HELP FOR docker_build

@TODO Make docs for docker functions
"
      ;;
      *)
        echo "
hook->command/help 050 : UNKNOWN scope for docker HELP MESSAGE GOES HERE [scope:$1]

- explain that this scope is not known

"
      ;;
    esac

  else

    echo "
hook->command/help 050 : GENERIC HELP MESSAGE GOES HERE

- explain the help system
- explain the docker library
- explain how to include the library and use it's functions

"

  fi
}
# list method
hook_help_docker_050_list()
{
  if [ -n "${1}" ]; then

    case "${1}" in
      "docker_build")
        echo "HELP TOPICS IN SCOPE FOR DOCKER:
--> docker_build : Build a new docker image from a local build (docker:docker_buid)"
      ;;
    esac

  else

    echo "LIST OF HELP TOPICS FOR DOCKER SCOPE"

  fi
}
