#!/bin/sh
#
#
#

hook_version=2
hook_root="hook_docker_run_post_020"

hook_docker_run_post_020_registerpath="${path_data}/containers"
ensure_folder "${hook_docker_run_post_020_registerpath}"

# description hook
hook_docker_run_post_020_descrtiption()
{
  echo "register any new containers in the system"
}

# help method
hook_docker_run_post_020_help()
{
  echo "
HOOK->DOCKER->RUN->POST->020 Register any new containers in the system

Any new container has a file created here: ${hook_docker_run_post_020_registerpath}

"
}

# execute method
hook_docker_run_post_020_execute()
{

echo "REGISTER CONTAINER WITH SYSTEM : $@"

}
