#!/bin/sh
#
# library: wwwserver-cnpm
#
# A library which includes some useful wwwserver builds, and
# some related settings
#

# The build code should automatically recognize our library
# and our settings are kept in the settings file
