#!/bin/sh
#
# HOOK->FEATURE->CREATE->PRE->300 Convert arguments to variables
#

hook_version=2
hook_root="hook_feature_create_pre_300"

# description method
hook_feature_create_pre_300_description()
{
  echo "Convert arguments to variables"
}

# Help method
hook_feature_create_pre_300_help()
{
  echo "HOOK->FEATURE->CREATE->PRE->300 Convert arguments to variables

"
}

# execute method
hook_feature_create_pre_300_execute()
{
  # define a var for the path for this particular feature
  feature_path="${path_features}"

  local flags=""
  while [ $# -gt 0 ]
  do
    case "$1" in
      -p|--path)
        feature_path="${2}"
        shift
        ;;
      *)
        break;
    esac
    shift
  done

  # set up the feature name
  feature_name="${feature_name:-${1}}"

  if [ -z "${feature_name}" ]; then
    message "No feature name provided, cannot create the feature"
    debug --level 5 --topic "FEATURE->CREATE" "No feature name provided, halting feature creation process"
    return 1
  fi
}
