#!/bin/sh
#
# Build the project image
#

hook_version=2
hook_root="hook_flow_init_030"


# description method
hook_flow_init_030_description()
{
  echo "build default project imags"
}

# help method
hook_flow_init_030_help()
{
  echo "
HOOK->FLOW->INIT->030: Build the default project image

[-b|--build {build}] : specify an alternate build that should be built

"
}

# execute method
hook_flow_init_030_execute()
{

  command_load build

  project_build=${project_build:-project}

  local flags=""
  while [ $# -gt 0 ]
  do
    case "$1" in
      -b|--build)
        project_build="${2}"
        shift
        ;;
      -i|--image)
        project_image="${2}"
        shift
        ;;
      -v|--version)
        project_version="${2}"
        shift
        ;;        
      *)
        break;
    esac
    shift
  done


  debug --level 6 --topic "HOOK->COMMAND->INIT->POST->030" "Building custom project build [build:${project_build}]"
  command_execute "build" --build "${project_build}" --image "${project_image}" --version "${project_version}"

}
