#!/bin/sh
#
# Build the project image
#

hook_version=2
hook_root="hook_command_init_post_030"


# description method
hook_command_init_post_030_description()
{
  echo "build default project imags"
}

# help method
hook_command_init_post_030_help()
{
  echo "
HOOK->FLOW->INIT->030: Build the default project image

[-b|--build {build}] : specify an alternate build that should be built

"
}

# execute method
hook_command_init_post_030_execute()
{

  command_include "build"

  project_build="${project_build:-template}"

  local flags=""
  while [ $# -gt 0 ]
  do
    case "$1" in
      -b|--build)
        project_build="${2}"
        shift
        ;;
      -i|--image)
        project_image="${2}"
        shift
        ;;
      -v|--version)
        project_version="${2}"
        shift
        ;;
      *)
        break;
    esac
    shift
  done

  if _docker_image_exists "${project_image}" -eq 0; then

    debug --level 5 --topic "HOOK->COMMAND->INIT->POST->030" "Custom project build already exists [build:${project_build}]"

  else

    debug --level 6 --topic "HOOK->COMMAND->INIT->POST->030" "Building custom project build [build:${project_build}]"
    command_execute "build" --build "${project_build}" --image "${project_image}" --version "${project_version}"

    if [ $? -eq 0 ]; then
      debug --level 5 --topic "HOOK->COMMAND->INIT->POST->030" "Built custom project build [build:${project_build}]"
    else
      debug --level 5 --topic "HOOK->COMMAND->INIT->POST->030" "Could not build custom project build [build:${project_build}]"
    fi
  fi
}
