#!/bin/sh
#
# Output core settings header
#

hook_version=2
hook_root="hook_settings_output_100"

# description method
hook_settings_output_100_description()
{
  echo "Output settings header"
}

# help method
hook_settings_output_100_help()
{
  echo "
hook->settings->output->100 : Output core settings header

Output the settings header, before any actual settings are output.

"
  help_topic_add "settings:settings"
  help_topic_list
}

# execute method
hook_settings_output_100_execute()
{
  echo "PROJECT SETTINGS
================"
}
