#!/bin/sh
#
# Output core settings
#

hook_version=2
hook_root="hook_settings_output_100"

# description method
hook_settings_output_100_description()
{
  echo "Output core settings"
}

# help method
hook_settings_output_100_help()
{
  echo "
hook->settings->output->100 : Output core settings

This is the core settings output hook, which will output settings used
in the core library.

"
  help_topic_add "settings:settings"
  help_topic_list
}

# execute method
hook_settings_output_100_execute()
{
  echo "
CORE SETTINGS OUTPUT
--------------------: [
### SINGLE PATHS USED ###
- path_project----------: ${path_project}
- path_execution--------: ${path_execution}
- path_library----------: ${path_library}
### SETTINGS LIBRARY PATHS ###
- path_userconf---------: ${path_userconf}
- path_projectconf------: ${path_projectconf}
### ALIASES ###
- active_aliases--------: `settings_output_list $(aliases_get)`
### LIBRARIES ###
- libraries loaded------: `settings_output_list $(libraries_list)`
]"
}

settings_output_list()
{
  echo ""
  local value
  for value in $@; do
    echo "      ${value}"
  done
}
