#!/bin/sh
#
# Docker Abstraction routines
#
#
# @NOTE I tried to focus on uniformity, so there are some
#       cases where functions take parametrized arguments
#       when serial arguments could have been used.
#
# @TODO make all functions echo the docker output, so that
#       calling code can catch the docker output?
#       Maybe don't do this; build has a long pause if you do

### methods #######################################

# (docker:docker_build)
#
# Build a new docker image from the Dockerfile
#
# -d|--dirty : leave all of the intermediate containers after the build
# -p|--path : path to the Dockerfile (default to "/conf"
# -i|--image : name to label the new image
# -q|--quiet : make the build quiet (there will be a long delay)
# -v|--version : build a specific version (defaults to latest)
#
# @TODO templating for Dockerfile, to substitute variables in ?
#   We could allow the Dockerfile to container shell vars, and pipe it
#   into the docker build process, but this would mean that 'ADD' commands
#   would need to be absolute
# @TODO templating for other files?
#
# @NOTE that templating with shell files isn't the best option,
# this should likely wait until a real toolset can be built using
# Python or Ruby.
#
docker_build() {
  local tag=""
  local clean="--rm=true"

  # default flags
  local flags=""
  while [ $# -gt 0 ]
  do
    case "$1" in
      -d|--dirty)
        clean=""
        ;;
      -i|--image)
        image="${2}"
        shift
        ;;
      -p|--path)
        path="${2}"
        shift
        ;;
      -v|--version)
        version="${2}"
        shift
        ;;
      *)
        break;; # terminate while loop
    esac
    shift
  done

  # Any additional arguments  after the image are passed to the docker run
  if [ $# -gt 0 ]; then
    flags="${flags} $@"
  fi

  # build a tag from the image and version (we always explicitly build a version, but default to "latest"
  [ -n "${image}" ] && tag="--tag=${image}:${version:-latest}"

  hooks_execute "docker/build" --state "pre" --image "${image}" --version "${version}" --path "${path}" --startargs $@

  # Run docker command
  debug --level 5 --topic "DOCKER->BUILD" "docker_build: [path:${path}][image:${image}][version:${version}][tag:${tag}] ==> docker build ${clean} ${tag} ${path}"
  docker build ${clean} ${tag} ${path}
  local success=$?
  if [ $success == 0 ]; then
    debug --level 6 --topic "DOCKER->BUILD" "Docker build run. '${image:-"Keyed"}' image created"
    hooks_execute "docker/build" --state "post" --image "${image}" --version "${version}" --path "${path}" --startargs $@
  else
    debug --level 2 --topic "DOCKER->BUILD" "Docker build failed."
    hooks_execute "docker/build" --state "fail" --image "${image}" --version "${version}" --path "${path}" --startargs $@
  fi
  return $success
}
# Destroy any build images
#
# -i|--image docker image to be removed
# -v|--version delete only a specific version
#
# -f|--force : delete an image, even if it is being used
#
# @NOTE delete an image with running containers does not stop the
#   containers, it doesn't actuall delete the image, but rather
#   it removes the label, and leaves the image.
#
# @TODO check for existing image before deleting
docker_rmi()
{

  # default flags
  local flags=""
  while [ $# -gt 0 ]
  do
    case "$1" in
      -f|--force)
        flags="${flags} --force"
        ;;
      -i|--image)
        image="${2}"
        shift
        ;;
      -v|--version)
        version="${2}"
        shift
        ;;
      *)
        break;; # terminate while loop
    esac
    shift
  done

  # build a proper image tag
  [ -n "${version}" ] && tag="${image}:${version}" || tag="${image}"

  hooks_execute "docker/rmi" --state "pre" --image "${image}" --version "${version}" --startargs $@

  # Run docker command
  debug --level 5 --topic "DOCKER" "docker_rmi [image:${image}][version:${version}][flags:${flags}][tag:${tag}] ==> docker rmi ${flags} ${tag}"
  docker rmi ${flags} ${tag}
  local success=$?
  if [ $success == 0 ]; then
    debug --level 6 --topic "DOCKER" "Docker rmi succeeded. \"${image}:${version}\" image removed"
    hooks_execute "docker/rmi" --state "post" --image "${image}" --version "${version}" --startargs $@
  else
    debug --level 2 --topic "DOCKER" "Docker rmi failed."
    hooks_execute "docker/rmi" --state "faile" --image "${image}" --version "${version}" --startargs $@
  fi
  return $sucess
}

#
# Start a built box
#
# Optionall use either a sheel or a command
# -c|--command "${command}" : run the provided command, instead of the default command.  NOTICE --shell, whci
# -s|--shell "${command:-"/bin/bash"}" : run the provided command, instead of the default command.  Defaults to /bin/bash
# Other Arguments
# -h|--hostname ${hostname} : define the hostname to be used
# -n|--name ${name} : define the container name
# -P|--allports ${name} : publish all opened ports for the container
# -t|--temporary : make the image temporary, so that it doesnt exists after it is shut down
# -u|--user : specify a container user to run the command
#
# $@ additional args for docker run
#
# @NOTE hooks are only run for background containers
#
# @TODO prevent both --shell and --command
# @TODO check for built image
# @TODO add flag for check if the image already has a running container (-s|--single)
# @TODO check execution success before running hook
docker_run()
{
  # default command: empty runs the build CMD command
  local command=""

  # if daemon then this, otherwise replace this (--shell replaces this with a shell command)
  local daemon="--detach=true"

  # default image and version, can be overriden with flags
  local image=${project_image}
  local version=${project_imageversion:-"latest"}

  # default flags
  local flags=""
  local hookflags=""
  while [ $# -gt 0 ]
  do
    case "$1" in
      -c|--container)
        flags="${flags} --name=\"$2\""
        hook_flags="${hook_flags} --container \"$2\""
        shift
        ;;
      -e|--execute)
        command="${2}"
        shift
        ;;
      -h|--hostname)
        flags="${flags} --hostname=\"$2\""
        shift
        ;;
      -i|--image)
        image="${2}"
        shift
        ;;
      -v|--version)
        version="${2}"
        shift
        ;;
      -P|--allports)
        flags="${flags} --publish-all=true"
        ;;
      -s|--shell)
        daemon=""
        flags="${flags} --tty=true --interactive=true"
        if [ "${2:0:1}" == "-" ]; then
          command="/bin/bash"
        else
          command="${2}"
          shift
        fi
        ;;
      -t|--temporary)
        flags="${flags} --rm"
        hook_flags="${hook_flags} --temporary"
        daemon=""
        ;;
      -u|--username) flags="${flags} --username=\"$2\"" && shift;;
      *)
        break;; # terminate while loop
    esac
    shift
  done

  # Any additional arguments  after the image are passed to the docker run
  if [ $# -gt 0 ]; then
    flags="${flags} $@"
  fi

  # Run docker command
  if [ "${daemon}" == "" ]; then
    # run the docker command in the foreground (no hooks are run in this case)
    debug --level 5 --topic "DOCKER->RUN" "docker_run (no-fork)[image:${image}][version:${version}][flags:${flags}][command:${command}] ==> docker run ${daemon} ${flags} ${image}:${version}  ${command}"
    docker run ${flags} ${image}:${version} ${command}
  else

    hooks_execute "docker/run" --state "pre" --image "${image}" --version "${version}" ${hook_flags} --startargs $@

    # run the docker command and capture the container ID
    debug --level 5 --topic "DOCKER->RUN" "docker_run (fork)[image:${image}][version:${version}][flags:${flags}][command:${command}] ==> docker run ${daemon} ${flags} ${image}:${version}  ${command}"
    local container="`docker run ${daemon} ${flags} ${image}:${version} ${command}`"
    local success=$?

    if [ $success -eq 0 ] && [ -n "${container}" ]; then
      local ip="`docker_inspect_getIP --container ${container}`"
      debug --level 5 --topic "DOCKER->RUN" "RESULTS of docker run => container started [ID:$container][ip:${ip}]"
      hooks_execute "docker/run" --state "post" --image "${image}" --version "${version}" --id "${container}" ${hook_flags} --ip "${ip}" --startargs $@
    else
      debug --level 2 --topic "DOCKER->RUN" "Docker run failed."
      hooks_execute "docker/run" --state "fail" --image "${image}" --version "${version}" --id "${container}" ${hook_flags} --ip "${ip}" --startargs $@
    fi

    return $success
  fi
}

#
# Attach to a running container`
#
# -c|--container : container ID or name
# -n|--noinput : don't attach stdin to the operation
# -s|--signlas : pass signals to the container
#
# @TODO parameter validation
# @TODO test if the container exists and is running
docker_attach()
{
  # start with an empty argument list
  local flags=""
  while [ $# -gt 0 ]
  do
    case "$1" in
      -c|--container)
        container="${2}"
        shift
        ;;
      -n|--noinput)
        flags="${flags} --no-stdin=true"
        ;;
      -s|--signals)
        flags="${flags} --sig-proxy=true"
        ;;
      -*) echo >&2 "docker_attach(): unknown flag $1 : attach [-n|--noinput] [-p|--sigproxy] -c|--container {container}";;
      *)
        break;; # terminate while loop
    esac
    shift
  done

  # execute pre hoosk
  hooks_execute "docker/attach" --state "pre" --image "${image}" --version "${version}" --container "${container}" ${flags} $@

  # Run docker command
  debug --level 5 --topic "DOCKER" "docker_attach [container:${container}][flags:${flags}] ==> docker attach ${flags} ${container}"
  docker attach ${flags} ${container}
  local success=$?
  if [ $success == 0 ]; then
    debug --level 6 --topic "DOCKER" "Docker attach succeeded. \"${container}\" container was attached"
    hooks_execute "docker/attach" --state "post" --image "${image}" --version "${version}" --container "${container}" ${flags} $@
  else
    debug --level 2 --topic "DOCKER" "Docker attach failed."
    hooks_execute "docker/attach" --state "fail" --image "${image}" --version "${version}" --container "${container}" ${flags} $@
  fi
  return $sucess
}

#
# Start a stopped box
#
# -c|--container : container ID or name
# $@ : additional arguments to pass to docker start
#
# @TODO validate parameters
# @TODO test if the container exists and is not running
docker_start()
{
  # start with an empty argument list
  local flags=""
  while [ $# -gt 0 ]
  do
    case "$1" in
      -c|--container)
        container="${2}"
        shift
        ;;
      -*) echo >&2 "docker_stop(): unknown flag $1 : stop -c|--container {container}";;
      *)
        break;; # terminate while loop
    esac
    shift
  done

  # Any additional arguments  after the image are passed to the docker start
  if [ $# -gt 0 ]; then
    flags="${flags} $@"
  fi

  # execute pre hooks
  hooks_execute "docker/start" --state "pre" --image "${image}" --version "${version}" --container "${container}" $@

  # Run docker command
  debug --level 5 --topic "DOCKER" "docker_start [container:${container}][flags:${flags}] ==> docker start ${flags} ${container}"
  docker start ${flags} ${container}
  local success=$?
  if [ $success == 0 ]; then
    local ip="`docker_inspect_getIP --container ${container}`"

    debug --level 6 --topic "DOCKER" "Docker start succeeded. \"${container}\" container started"
    hooks_execute "docker/start" --state "post" --image "${image}" --version "${version}" --container "${container}" --ip "${ip}" $@
  else
    debug --level 2 --topic "DOCKER" "Docker start failed."
    hooks_execute "docker/start" --state "fail" --image "${image}" --version "${version}" --container "${container}" $@
  fi
  return $sucess
}

#
# Stop a running box
#
# -c|--container : container ID or name
# $@ : additional arguments to pass to docker kill
#
# @TODO validate parameters
# @TODO test if the container exists and is running
docker_stop()
{
  # start with an empty argument list
  local flags=""
  while [ $# -gt 0 ]
  do
    case "$1" in
      -c|--container)
        container="${2}"
        shift
        ;;
      -c|--time)
        flags="${flags} --time=$2"
        shift
        ;;
      -*) echo >&2 "docker_stop(): unknown flag $1 : stop -c|--container {container} [-t|--time {seconds}]";;
      *)
        break;; # terminate while loop
    esac
    shift
  done

  # Any additional arguments  after the image are passed to the docker run
  if [ $# -gt 0 ]; then
    flags="${flags} $@"
  fi

  # execute pre hooks
  hooks_execute "docker/stop" --state "post" --image "${image}" --version "${version}" --container "${container}" $@

  # Run docker command
  debug --level 5 --topic "DOCKER" "docker_stop [container:${container}][flags:${flags}] ==> docker stop ${flags} ${container}"
  docker stop ${flags} ${container}
  local success=$?
  if [ $success == 0 ]; then
    debug --level 6 --topic "DOCKER" "Docker stop succeeded. \"${container}\" container stopped"
    hooks_execute "docker/stop" --state "post" --image "${image}" --version "${version}" --container "${container}" $@
  else
    debug --level 2 --topic "DOCKER" "Docker stop failed."
    hooks_execute "docker/stop" --state "fail" --image "${image}" --version "${version}" --container "${container}" $@
  fi
  return $sucess
}

#
# Delete any container
#
# -c|--container : container to remove
#
# @NOTE you can use the --rm flag in docker run to make a container temporary.
#
# @TODO validate parameters
# @TODO check if container exists
# @TODO stop container if running ?
docker_rm()
{

  # hook to call after removing
  hook=""

  # start with an empty argument list
  local flags=""
  while [ $# -gt 0 ]
  do
    case "$1" in
      -c|--container)
        container="${2}"
        shift
        ;;
      -*) echo >&2 "docker_rm(): unknown flag $1 : rm -c|--container {container}";;
      *)
        break;; # terminate while loop
    esac
    shift
  done

  # Any additional arguments  after the image are passed to the docker run
  if [ $# -gt 0 ]; then
    flags="${flags} $@"
  fi

  # execute any existing hooks
  hooks_execute "docker/rm" --state "pre" --container "${container}"

  # Run docker command
  debug --level 5 --topic "DOCKER" "docker_rm [container:${container}][flags:${flags}] ==> docker rm ${flags} ${container}"
  docker rm ${flags} ${container}
  local success=$?
  if [ $success == 0 ]; then
    debug --level 6 --topic "DOCKER" "Docker rm succeeded. \"${container}\" container removed"
    hooks_execute "docker/rm" --state "post" --container "${container}" $@
  else
    debug --level 2 --topic "DOCKER" "Docker rm failed."
    hooks_execute "docker/rm" --state "fail" --container "${container}" $@
  fi
  return $sucess
}

#
# Commit an existing container to an image:version
#
# $1 : image to be saved
# $2 : image version to be saved
# $3 : container to be saved
#
# @TODO parameter validation
# @TODO check for built image
# @TODO check for existing container
docker_commit()
{
  # default flags
  local flags=""
  while [ $# -gt 0 ]
  do
    case "$1" in
      -c|--container)
        container="${2}"
        shift
        ;;
      -i|--image)
        image="${2}"
        shift
        ;;
      -v|--version)
        version="${2}"
        shift
        ;;
      *)
        break;; # terminate while loop
    esac
    shift
  done

  # execute any existing hooks
  hooks_execute attach --state pre --image "${image}" --version "${version}" --container "${container}" $@

  # Run docker command
  debug --level 5 --topic "DOCKER" "docker_commit [image:${image}][version:${version}][container:${container}][flags:${flags}] ==> docker commit ${container} ${image}:${version}"
  docker commit ${flags} ${container} ${image}:${version}
  local success=$?
  if [ $success == 0 ]; then
    debug --level 6 --topic "DOCKER" "Docker commit succeeded. \"${container}\" container committed to ${image}:${version}"
    hooks_execute "docker/attach" --state "post" --image "${image}" --version "${version}" --container "${container}" $@
  else
    debug --level 2 --topic "DOCKER" "Docker commit failed."
    hooks_execute "docker/attach" --state "fail" --image "${image}" --version "${version}" --container "${container}" $@
  fi
  return $sucess
}

#
# Pause a running container`
#
# -c|--container : container ID or name
#
# @TODO parameter validation
# @TODO test if the container exists and is running
# @TODO test if the container is not paused already
docker_pause()
{
  # start with an empty argument list
  local flags=""
  while [ $# -gt 0 ]
  do
    case "$1" in
      -c|--container)
        container="${2}"
        shift
        ;;
      -*) echo >&2 "docker_pause(): unknown flag $1 : pause -c|--container {container}";;
      *)
        break;; # terminate while loop
    esac
    shift
  done

  # execute pre hooks
  hooks_execute "docker/pause" --state "pre" --container "${container}" $@

  # Run docker command
  debug --level 5 --topic "DOCKER" "docker_pause [container:${container}][flags:${flags}] ==> docker pause ${flags} ${container}"
  docker pause ${flags} ${container}
  local success=$?
  if [ $success == 0 ]; then
    debug --level 6 --topic "DOCKER" "Docker pause succeeded. \"${container}\" container was paused"
    hooks_execute "docker/pause" --state "post" --container "${container}" $@
  else
    debug --level 2 --topic "DOCKER" "Docker pause failed."
    hooks_execute "docker/pause" --state "post" --container "${container}" $@
  fi
  return $sucess
}

#
# Un-Pause a paused  container`
#
# -c|--container : container ID or name
#
# @TODO parameter validation
# @TODO test if the container exists and is running
# @TODO test if the container is paused
docker_unpause()
{
  # start with an empty argument list
  local flags=""
  while [ $# -gt 0 ]
  do
    case "$1" in
      -c|--container)
        container="${2}"
        shift
        ;;
      -*) echo >&2 "docker_unpause(): unknown flag $1 : unpause -c|--container {container}";;
      *)
        break;; # terminate while loop
    esac
    shift
  done

  # execute pre hooks
  hooks_execute "docker/unpause" --state "pre" --container "${container}" $@

  # Run docker command
  debug --level 5 --topic "DOCKER" "docker_unpause [container:${container}][flags:${flags}] ==> docker unpause ${flags} ${container}"
  docker unpause ${flags} ${container}
  local success=$?
  if [ $success == 0 ]; then
    debug --level 6 --topic "DOCKER" "Docker unpause succeeded. \"${container}\" container was unpaused"
    hooks_execute "docker/unpause" --state "post" --container "${container}" $@
  else
    debug --level 2 --topic "DOCKER" "Docker unpause failed."
    hooks_execute "docker/unpause" --state "fail" --container "${container}" $@
  fi
  return $sucess
}


#
# Execute a command inside any container
#
# -c|--container : container to execute inside of
#
# -d, --detach         Detached mode: run command in the background
# -i, --interactive    Keep STDIN open even if not attached
# -t, --tty            Allocate a pseudo-TTY
#
# @TODO validate parameters
# @TODO check if container exists
# @TODO stop container if running ?
docker_exec()
{

  # hook to call after removing
  hook=""

  # start with an empty argument list
  local flags=""
  while [ $# -gt 0 ]
  do
    case "$1" in
      -c|--container)
        container="${2}"
        shift
        ;;
      -d|detach)
	flags="${flags} --detach=true"
	;;
      -i|--interactive)
	flags="${flags} --interactive=true"
	;;
      -t|--tty)
	flags="${flags} --tty=true"
	;;
      -*) echo >&2 "docker_execute(): unknown flag $1 : execute -c|--container {container}";;
      *)
        break;; # terminate while loop
    esac
    shift
  done

  # execute any existing hooks
  hooks_execute "docker/execute" --state "pre" --container "${container}"

  # Run docker command
  debug --level 5 --topic "DOCKER" "docker_execute [container:${container}][flags:${flags}] ==> docker exec ${flags} ${container} $@"
  docker exec ${flags} ${container} $@
  local success=$?
  if [ $success == 0 ]; then
    debug --level 6 --topic "DOCKER" "Docker execute succeeded."
    hooks_execute "docker/execute" --state "post" --container "${container}" $@
  else
    debug --level 2 --topic "DOCKER" "Docker execute failed."
    hooks_execute "docker/execute" --state "fail" --container "${container}" $@
  fi
  return $sucess
}

#
# List running processes in a container
#
# -c|--container : which container to list
#
docker_top()
{
  # default flags
  local flags=""
  while [ $# -gt 0 ]
  do
    case "$1" in
      -c|--container)
        container="${2}"
        shift
        ;;
      *)
        break;; # terminate while loop
    esac
    shift
  done

  # Run docker command
  debug --level 5 --topic "DOCKER" "docker_top [container:${container}][flags:${flags}] ==> docker top ${flags} ${container}"
  docker top ${flags} ${container}

  local success=$?
  return $sucess
}

#
# Show the log/console output for a container
#
# -c|--container : which container to list
#
docker_logs()
{
  # default flags
  local flags=""
  while [ $# -gt 0 ]
  do
    case "$1" in
      -c|--container)
        container="${2}"
        shift
        ;;
      *)
        break;; # terminate while loop
    esac
    shift
  done

  # Run docker command
  debug --level 5 --topic "DOCKER" "docker_logs [container:${container}][flags:${flags}] ==> docker logs ${flags} ${container}"
  docker logs ${flags} ${container}
  local success=$?
  return $sucess
}

#
# Get the inspect JSON for the container
#
# @NOTE that JSON is not very usefull, but if it was
# then you could get all of the info that you want
# about your container from this:
# - base image
# - IP
# - forarded ports (already can get this from ps
#
# $1 : docker container
#
docker_inspect()
{
  # default flags
  local flags=""
  while [ $# -gt 0 ]
  do
    case "$1" in
      -c|--container)
        container="${2}"
        shift
        ;;
      -f|--format)
        flags="${flags} --format=\"${2}\""
        shift
        ;;
      *)
        break;; # terminate while loop
    esac
    shift
  done

  # Run docker command
  debug --level 9 --topic "DOCKER" "docker_inspect [container:${container}][flags:${flags}] ==> docker inspect ${flags} ${container}"
  docker inspect ${flags} "${container}"
  return $?
}
# get the IP address for a container
docker_inspect_getIP()
{
  while [ $# -gt 0 ]
  do
    case "$1" in
      -c|--container)
        container="${2}"
        shift
        ;;
      *)
        break;; # terminate while loop
    esac
    shift
  done

  debug --level 9 --topic "DOCKER->INSPECT->GETIP" "get ip [container:${container}] ==> docker_inspect --format \"{{ .NetworkSettings.IPAddress }}\" --container \"${container}\""
  docker inspect --format="{{ .NetworkSettings.IPAddress }}" "${container}"
}

#
# Check if an image exists,
#
# -i|--image {image} : image to filter for, you can add a version "${image}:${version}"
# -a|--all : @NOTE removed - this would search all build commits, which is really not something we want.
# -q|--idonly : return only image IDs
#
docker_inspect_image_list()
{
  # filter text for grep
  local filter=""

  # start with an empty argument list
  local flags="| sed \"1 d\" "
  while [ $# -gt 0 ]
  do
    case "$1" in\
      -d|--id)
        # this is a container id
        filter="${filter} | grep -i \"\\s${2:0:12}\\s\" "
        shift
        ;;
      -i|--image)
        filter="${filter} | grep -i \"^${2}\\s\" "
        shift
        ;;
      -v|--version)
        filter="${filter} | grep -i \"\\s${2}\\s\" "
        shift
        ;;
      -q|--idonly)  flags="$flags --quiet";;
      *)
          break;; # terminate while loop
    esac
    shift
  done

  # Run docker command
  debug --level 9 --topic "DOCKER" "docker_inspect_image_list [flags:${flags}][filter:${filter}] ==> docker images ${flags} ${filter}"
  eval "docker images ${flags} ${filter}"

}

# check if docker image $1 exists (has been built)
docker_image_exists()
{
  local image=$1

  if [ "${image##*:}" == "${image}" ]; then
    local exists="`docker_inspect_image_list --image \"${image}\"`"
    local success=$?
    debug --level 6 --topic "DOCKER" "docker_image_exists [image:${image}] ==> docker_inspect_image_list --image ${image} ==> ${exists}"
  else
    local exists="`docker_inspect_image_list --image \"${image%%:*}\" --version \"${image##*:}\"`"
    local success=$?
    debug --level 6 --topic "DOCKER" "docker_image_exists [image:${image%%:*}][version:${image##*:}] ==> docker_inspect_image_list --image ${image%%:*} --version ${image##*:} ==> ${exists}"
  fi

  if [ $success ] && [ -n "${exists}" ]; then
    return 0
  else
    return 1
  fi
}


#
# Check if a container exists - and if it is running
#
# -c|container {container} : container name or ID to filter for (@NOTE Filter arg)
# -i|--image {image} : image name to filter for (@NOTE Filter arg)
# -v|--version {version} : image version to filter for (@NOTE Filter arg)
#
# AND
# -r|--running : only check for running containers
# -q|--id : return only the container ID
#
# @NOTE while this has multiple filter options, it only handles one at a time
# @NOTE if not filters are passed,
#
# @TODO allow retrieval of just specific fields from docker_ps
# @TODO make this function handle multiple filters per execution.
docker_inspect_container_list()
{
  # assume we want to check even for containers that are not running
  local all="--all"
  # start with an empty argument list
  local flags=""

  # text for which we will grep
  local filter="| sed \"1 d\" "

  while [ $# -gt 0 ]
  do
    case "$1" in
      -n|--name)
        # this is a container name
        # Not sure why \s doesn't work here ?!?
        filter="${filter} | grep -i \"[ ,]${2} .*$\" "
        shift
        ;;
      -d|--id)
        # this is a container id
        filter="${filter} | grep -i \"^${2:0:12}\\s\" "
        shift
        ;;
      -i|--image)
        filter="${filter} | grep -i \"\\s${2}:\" "
        shift
        ;;
      -v|--version)
        filter="${filter} | grep -i \":${2}\\s\" "
        shift
        ;;
      -q|--idonly)  flags="$flags --quiet";;
      -r|--running)  all="";;
      -*) echo >&2 "docker_container_list(): unknown flag $1 : exists [-n|--name {container}] [-d|--id {id}] [-q|--idonly] [-r|--running] -c|--container {container} ]";;
      *)
          break;; # terminate while loop
    esac
    shift
  done

  # Run docker command
  debug --level 9 --topic "DOCKER" "docker_inspect_container_list listing the docker container => docker ps ${flags} ${all} ${filter}"
  eval "docker ps ${flags} ${all} ${filter}"
  return $?
}


# check if docker container $1 exists (has ever been started with `docker run`)
docker_container_exists()
{
  local container=$1

  local exists="`docker_inspect_container_list --name $container`"
  local success=$?
  debug --level 7 --topic "DOCKER" "_docker_container_exists [container:$container] ==> docker_inspect_container_list --name $container ==> ${exists}"

  if [ $success ] && [ -n "$exists" ]; then
    return 0
  else
    return 1
  fi
}
# check if docker container $1 is running
docker_container_running()
{
  local container=$1

  local running="`docker_inspect_container_list --running --name $container`"

  debug --level 7 --topic "DOCKER" "_docker_container_running [container:$container] ==> docker_inspect_container_list --running --name $container ==> ${running}"

  if [ -n "$running" ]; then
    return 0
  else
    return 1
  fi
}

# check if any docker containers using image $1 are running
docker_image_running()
{
  local image=$1

  if [ "${image##*:}" == "${image}" ]; then
    local running="`docker_inspect_image_list --image \"${image}\"`"
    local success=$?
    debug --level 7 --topic "DOCKER" "_docker_image_running [image:${image}] ==> docker_inspect_container_list --running --image ${image} ==> ${running}"
  else
    local running="`docker_inspect_container_list --image \"${image%%:*}\" --version \"${image##*:}\"`"
    local success=$?
    debug --level 7 --topic "DOCKER" "_docker_image_running [image:${image}] ==> docker_inspect_container_list --running --image ${image%%:*} --version ${image##*:}==> ${running}"
  fi

  if [ -n "${running}" ]; then
    return 0
  else
    return 1
  fi
}
