#!/bin/sh
#
# Docker Library

# initialize the docker library
docker_init()
{
  local path=""
  # default flags
  local flags=""
  while [ $# -gt 0 ]
  do
    case "$1" in
       --path)
        path="${2}"
        shift
        ;;
      *)
        break;; # terminate while loop
    esac
    shift
  done

  path_include "${path}/api" $@
}
