#!/bin/sh
#
# Docker Library

# initialize the docker library
docker_init()
{
  local path=""

  # default flags
  local flags=""
  while [ $# -gt 0 ]
  do
    case "$1" in
       --source-include-path)
        path="${2}"
        shift
        ;;
      *)
        break;; # terminate while loop
    esac
    shift
  done

  _include_source "${path}/docker.api" $@

  _lib_docker_init=$?
}

# this should be moved into the library routines and run automatically on ever lib
_lib_docker_init=${_lib_docker_init:--1}
if [ $_lib_docker_init -eq -1 ]; then
  docker_init $@
fi


