#!/bin/sh
#
# Help hander
#

# execute method
docker_help()
{
  if [ -n "${1}" ]; then

    case "${1}" in
      "docker_build")
        echo "
HELP FOR docker_build

@TODO Make docs for docker build function
"
      ;;
      *)
        echo "Unknown docker help topic : $1

You asked for help on an unknow docker topic

"
      ;;
    esac

  else

    echo "Help for the Docker library

The Docker library is a toolset/API library that provides low-level functions
that do the lifting for docker integration.  These functions are callable to
do all of the docker tasks, test values, and retrieve information from containers
and images.

@Note that the docker functions are not aware of the project settings, and so
  passing of arguments into the functions is essential.

@TODO this topic list is quite incomplete and needs more work
"

    help_scope_add "docker"
    help_scope_list

  fi
}
# list method
docker_helplist()
{
  if [ -n "${1}" ]; then

    case "${1}" in
      "docker_build")
        echo "HELP TOPICS IN SCOPE FOR DOCKER:
--> docker_build : Build a new docker image from a local build (docker:docker_buid)"
        ;;
      "docker")
        echo "LIST OF HELP TOPICS FOR DOCKER SCOPE - @TODO this will be a list of all of the docker functions
--> docker_build : Build a new docker image from a local build (docker:docker_buid)"
        ;;
      *)
        echo "UNKNOWN DOCKER HELP LIST SCOPE ${1}"
        ;;
    esac

  fi
}
