#!/usr/bin/env bash
#
# This alias just packages some popular status flow topic sets
#

while [ $# -gt 0 ]
do
  case "$1" in
    --source-include-path)
      shift
      ;;
    --target)

      # Add status topics in sets
      case "${2}" in
        classic)
          # this used to be the old behaviour of the status flow
          flow_status_topics="${flow_status_topics} build image container.active"
          ;;
        containers|cont|c)
          flow_status_topics="${flow_status_topics} container"
          ;;
      esac
      shift

      ;;
    *)
      break;
  esac
  shift
done
