#!/bin/sh
#
# COMMAND: List containers
#

# Help function
ps_help()
{
 echo "
List processes running inside a container

  -c|--container {container} : override the default container name with an ID or name of a running container

"
}

# command execute function
ps_execute()
{
  local container=${project_container}

  while [ $# -gt 0 ]
  do
    case "$1" in
      -c|--container)
        container="${2}"
        shift
        ;;
      -*)
        echo >&2 "unknown flag $1 : ps [-c|--container] {container}"
        exit
        ;;
      *)
        break;
    esac
    shift
  done

  if docker_container_running "${container}"; then

    # Run the ps function
    debug --level 5 --topic "COMMAND->PS" "handing off to docker abstraction ==> docker_top --container ${container}"
    docker_top --container "${container}"

    return 0

  # start a new container based on the image
  else

    if docker_container_exists "${container}"; then
      # Run the run function
      debug --level 5 --topic "COMMAND->PS" "container is not running ${container}"
    else
      debug --level 5 --topic "COMMAND->PS" "container does not exist ${container}"
    fi
    return 1

  fi

}
