#!/bin/sh
#
# COMMAND: Remove a container
#

# command description function
remove_description()
{
  echo "Delete a container"
}

# Command help function
remove_help()
{
  echo "
Delete the container

  -c|--container {container} : override the default container name with an ID or name of a running container

@NOTE this does not remove the image, for that try the destroy command
@TODO ask for confirmation
"
}

# command execute function
remove_execute()
{
  container=${project_container}

  while [ $# -gt 0 ]
  do
    case "$1" in
      -c|--container)
        container="${2}"
        shift
        ;;
      -*)
        echo >&2 "unknown flag $1 : remove [-c|--container] {container}"
        exit
        ;;
      *)
        break;
    esac
    shift
  done

  if docker_container_exists ${container}; then
#     if  docker_container_running ${container}; then
#       message "Could not remove container (${container}) from system.  The container exists, but is still running.  Stop it first."
#
#       debug --level 4 --topic "COMMAND->REMOVE" "docker remove not executed.  The container exists but is running.  Stop it first [container:${container}]"
#       return 1
#
#     else
      message "Deleting/Removing container (${container}) from system"

      # Run the rm function
      debug --level 5 --topic "COMMAND->REMOVE" "remove [ handing off to docker abstraction ] ==> docker_rm --container ${container}"
      docker_rm --container "${container}"
      return $?

#     fi

  else
    message "Could not remove container (${container}) from the system as it does not exist."

    debug --level 4 --topic "COMMAND->REMOVE" "docker remove not executed.  The container does not exist [container:${container}]"
    return 1
  fi

}
