#!/bin/sh
#
# COMMAND: Remove a container
#

# Command help function
remove_help()
{
  echo "
Delete the container

  -c|--container {container} : override the default container name with an ID or name of a running container

@TODO ask for confirmation
"
}

# command execute function
remove_execute()
{
  container=${project_container}

  while [ $# -gt 0 ]
  do
    case "$1" in
      -c|--container)
        container="${2}"
        shift
        ;;
      -*)
        echo >&2 "unknown flag $1 : stop [-c|--container] {container}"
        exit
        ;;
      *)
        break;
    esac
    shift
  done


  if _docker_container_exists ${container}; then

    if  _docker_container_running ${container}; then

      debug --level 2 --topic "COMMAND->REMOVE" "docker remove not executed.  The container exists but is running.  Stop it first [container:${container}]"
      return 1

    else

      # Run the rm function
      debug --level 5 --topic "COMMAND->REMOVE" "remove [ handing off to docker abstraction ] ==> docker_rm --container ${container}"
      docker_rm --container "${container}"
      return $?

    fi

  else

    debug --level 2 --topic "COMMAND->REMOVE" "docker remove not executed.  The container does not exist [container:${container}]"
    return 1
  fi

}
