#!/bin/sh
#
# COMMAND: Run a command in a temporary container
#

# Command help function
run_help()
{
  echo "
Run a command in a new container.

@NOTE this container is temporary, unless you pass --peristant

@NOTE if you pass no command, then the default \${machine_shell} command is used
"
}

# Command execute function
run_execute()
{
  local image="${project_image}"
  local version="${project_imageversion}"
  local hostname="${machine_hostname}"
  local name=""

  # temp.  empty this to make the run a persistant container
  local temp="--temporary"

  local flags=""
  while [ $# -gt 0 ]
  do
    case "$1" in
      -c|--container)
        name="$2"
        shift
        ;;
      -h|--hostname)
        hostname="${2}"
        shift
        ;;
      -i|--image)
        image="${2}"
        shift
        ;;
      -r|--persistant)
        temp=""
        ;;
      -v|--version)
        version="${2}"
        shift
        ;;
      *)
        break;
    esac
    shift
  done

  if [ "${name}" == "" ]; then
    name="${image}_${version}"
  fi

  # use the machine run or pass in a command
  command=${@:-${Machine_shell}}

  # add default flags to the end of the flag list
  flags="${flags} ${Machine_shellrunargs} ${Machine_mountvolumes}"

  # Run the run function
  debug --level 5 --topic "COMMAND" "run [ handing off to docker abstraction ] ==> docker_run ${temp} --image /"${image}/" --version /"${version}/" --hostname /"${hostname}/" --name /"${name}/" --command /"${command}/" ${flags} $@/"
  docker_run ${temp} --image "${image}" --version "${version}" --hostname "${hostname}" --name "${name}" --command "${command}" ${flags} $@
  return $?
}
