#!/bin/sh
#
# COMMAND: Get access to a shell running on a certain image
#

# Command help function
shell_help()
{
  echo "
Give shell access to a new container based on the image
this does not term into a running container, but rather
creates a new container and gives shell access to it
"
}

# Command execute function
shell_execute()
{
  image="${project_image}"
  version="${project_imageversion}"
  hostname="${machine_hostname}"

  # temp.  empty this to make the shell a persistant container
  temp="--temporary"

  flags=""
  while [ $# -gt 0 ]
  do
    case "$1" in
      -c|--container)
        flags="${flags} --name $2"
        shift
        ;;
      -h|--hostname)
        hostname="${2}"
        shift
        ;;
      -i|--image)
        image="${2}"
        shift
        ;;
      -r|--persistant)
        temp=""
        ;;
      -v|--version)
        version="${2}"
        shift
        ;;
      *)
        break;
    esac
    shift
  done

  # use the machine shell or pass in a command
  command=${@:-${machine_shell}}

  # add default flags to the end of the flag list
  flags="${flags} ${machine_shellrunargs} ${machine_mountvolumes}"

  # Run the shell function
  debug --level 5 --topic "COMMAND" "shell [ handing off to docker abstraction ] ==> docker_run ${temp} --shell \"${command}\" --image \"${image}\" --version \"${version}\" --hostname \"${hostname}\" ${flags} $@"
  docker_run ${temp} --shell "${command}" --image "${image}" --version "${version}" --hostname "${hostname}" ${flags} $@
  return $?
}
