#!/bin/sh
#
# COMMAND: Stop any running containers
#

# Command help function
stop_help()
{
  echo "
Stop the container if it is running

  -c|--container {container} : override the default container name with an ID or name of a running container

"
}

# command execute function
stop_execute()
{
  container=${project_container}

  flags=""
  while [ $# -gt 0 ]
  do
    case "$1" in
      -c|--container)
        container="${2}"
        shift
        ;;
      -*)
        echo >&2 "unknown flag $1 : stop [-c|--container] {container}"
        exit
        ;;
      *)
        break;
    esac
    shift
  done


  if _docker_container_running ${container}; then
    # Run the stop function
    debug --level 5 --topic "COMMAND->STOP" "handing off to docker abstraction [container:${container}] ==> docker_stop --container ${container}"
    local container=$(docker_stop --container "${container}")
    return $?

  else

    if _docker_container_exists ${container}; then
      debug --level 2 --topic "COMMAND->STOP" "docker stop not executed.  The container exists but is not running [container:${container}]"
    else
      debug --level 2 --topic "COMMAND->STOP" "docker stop not executed.  The container does not exist [container:${container}]"
    fi
    return 1
  fi
}
