#!/bin/sh
#
# COMMAND: Stop any running containers
#

# command description function
shell_description()
{
  echo "Stop a running container"
}

# Command help function
stop_help()
{
  echo "
Stop the container if it is running

  -c|--container {container} : override the default container name with an ID or name of a running container
  -t|--time {seconds} : number of seconds to wait before stopping the container (defaul is 0)
"
}

# command execute function
stop_execute()
{
  local container=${project_container}
  local seconds=0

  flags=""
  while [ $# -gt 0 ]
  do
    case "$1" in
      -c|--container)
        container="${2}"
        shift
        ;;
      -t|--time)
        seconds="${2}"
        shift
        ;;
      -*)
        echo >&2 "unknown flag $1 : stop [-c|--container] {container}"
        exit
        ;;
      *)
        break;
    esac
    shift
  done

  if docker_container_running "${container}"; then
    flags="${flags} --time ${seconds}"

    message "Now stopping running container (${container})"

    # Run the stop function
    debug --level 5 --topic "COMMAND->STOP" "handing off to docker abstraction [container:${container}] ==> docker_stop --container \"${container}\" ${flags}"
    local container=$(docker_stop --container "${container}" ${flags})
    return $?

  else

    if docker_container_exists "${container}"; then
      message "Could not stop container (${container}) as it was not running"
      debug --level 5 --topic "COMMAND->STOP" "docker stop not executed.  The container exists but is not running [container:${container}]"
    else
      message "Could not stop container (${container}) as it does not exist."
      debug --level 5 --topic "COMMAND->STOP" "docker stop not executed.  The container does not exist [container:${container}]"
    fi
    return 1
  fi
}
